def load(h):
    return ({'abbr': 'air', 'code': 0, 'title': 'Air'},
            {'abbr': 'ozone', 'code': 1, 'title': 'Ozone'},
            {'abbr': 'water', 'code': 2, 'title': 'Water vapour'},
            {'abbr': 'methane', 'code': 3, 'title': 'Methane'},
            {'abbr': 'carbonDioxide', 'code': 4, 'title': 'Carbon dioxide'},
            {'abbr': 'carbonMonoxide', 'code': 5, 'title': 'Carbon monoxide'},
            {'abbr': 'nitrogenDioxide', 'code': 6, 'title': 'Nitrogen dioxide'},
            {'abbr': 'nitrousOxide', 'code': 7, 'title': 'Nitrous oxide'},
            {'abbr': 8, 'code': 8, 'title': 'Nitrogen monoxide'},
            {'abbr': 9, 'code': 9, 'title': 'Formaldehyde'},
            {'abbr': 10, 'code': 10, 'title': 'Sulphur dioxide'},
            {'abbr': 11, 'code': 11, 'title': 'Nitric acid'},
            {'abbr': 'noy',
             'code': 12,
             'title': 'All nitrogen oxides (NOy) expressed as nitrogen'},
            {'abbr': 13, 'code': 13, 'title': 'Peroxyacetyl nitrate'},
            {'abbr': 14, 'code': 14, 'title': 'Hydroxyl radical'},
            {'abbr': 15, 'code': 15, 'title': 'Ammonia'},
            {'abbr': 16, 'code': 16, 'title': 'Ammonium'},
            {'abbr': 17, 'code': 17, 'title': 'Radon'},
            {'abbr': 18, 'code': 18, 'title': 'Dimethyl sulphide'},
            {'abbr': 'hexachlorocyclohexane',
             'code': 19,
             'title': 'Hexachlorocyclohexane'},
            {'abbr': 20, 'code': 20, 'title': 'Alpha hexachlorocyclohexane'},
            {'abbr': 21, 'code': 21, 'title': 'Elemental mercury'},
            {'abbr': 22, 'code': 22, 'title': 'Divalent mercury'},
            {'abbr': 23, 'code': 23, 'title': 'Hexachlorobiphenyl'},
            {'abbr': 'nox', 'code': 24, 'title': 'NOx expressed as nitrogen'},
            {'abbr': 'nmvoc',
             'code': 25,
             'title': 'Non-methane volatile organic compounds expressed as carbon'},
            {'abbr': 'anmvoc',
             'code': 26,
             'title': 'Anthropogenic non-methane volatile organic compounds expressed as '
                      'carbon'},
            {'abbr': 'bnmvoc',
             'code': 27,
             'title': 'Biogenic non-methane volatile organic compounds expressed as '
                      'carbon'},
            {'abbr': 40000, 'code': 40000, 'title': 'Sulphate dry aerosol'},
            {'abbr': 40001, 'code': 40001, 'title': 'Black carbon dry aerosol'},
            {'abbr': 40002,
             'code': 40002,
             'title': 'Particulate organic matter dry aerosol'},
            {'abbr': 40003,
             'code': 40003,
             'title': 'Primary particulate organic matter dry aerosol'},
            {'abbr': 40004,
             'code': 40004,
             'title': 'Secondary particulate organic matter dry aerosol'},
            {'abbr': 40005, 'code': 40005, 'title': 'Sea salt dry aerosol'},
            {'abbr': 40006, 'code': 40006, 'title': 'Dust dry aerosol'},
            {'abbr': 40007, 'code': 40007, 'title': 'Mercury dry aerosol'},
            {'abbr': 40008, 'code': 40008, 'title': 'PM10 aerosol'},
            {'abbr': 40009, 'code': 40009, 'title': 'PM2P5 aerosol'},
            {'abbr': 40010, 'code': 40010, 'title': 'PM1 aerosol'},
            {'abbr': 40011, 'code': 40011, 'title': 'Nitrate dry aerosol'},
            {'abbr': 40012, 'code': 40012, 'title': 'Ammonium dry aerosol'},
            {'abbr': 40013, 'code': 40013, 'title': 'Water in ambient aerosol'},
            {'abbr': 65535, 'code': 65535, 'title': 'Missing'})
