def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Net short-wave radiation flux (surface)',
             'units': 'W m-2'},
            {'abbr': 1,
             'code': 1,
             'title': 'Net short-wave radiation flux (top of atmosphere)',
             'units': 'W m-2'},
            {'abbr': 2, 'code': 2, 'title': 'Short wave radiation flux', 'units': 'W m-2'},
            {'abbr': 3, 'code': 3, 'title': 'Global radiation flux', 'units': 'W m-2'},
            {'abbr': 4, 'code': 4, 'title': 'Brightness temperature', 'units': 'K'},
            {'abbr': 5,
             'code': 5,
             'title': 'Radiance (with respect to wave number)',
             'units': 'W m-1 sr-1'},
            {'abbr': 6,
             'code': 6,
             'title': 'Radiance (with respect to wave length)',
             'units': 'W m-3 sr-1'},
            {'abbr': 7,
             'code': 7,
             'title': 'Downward short-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 8,
             'code': 9,
             'title': 'Upward short-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
