def load(h):
    return ({'abbr': 'grg1', 'code': 1, 'title': 'GRG1 GRG1/MOZART specie kg/kg'},
            {'abbr': 'grg2', 'code': 2, 'title': 'GRG2 GRG2/MOZART specie kg/kg'},
            {'abbr': 'grg3', 'code': 3, 'title': 'GRG3 GRG3/MOZART specie kg/kg'},
            {'abbr': 'grg4', 'code': 4, 'title': 'GRG4 GRG4/MOZART specie kg/kg'},
            {'abbr': 'grg5', 'code': 5, 'title': 'GRG5 GRG5/MOZART specie kg/kg'},
            {'abbr': 'vis-340',
             'code': 100,
             'title': 'VIS-340 VIS-340/Visibility at 340 nm m'},
            {'abbr': 'vis-355',
             'code': 101,
             'title': 'VIS-355 VIS-355/Visibility at 355 nm m'},
            {'abbr': 'vis-380',
             'code': 102,
             'title': 'VIS-380 VIS-380/Visibility at 380 nm m'},
            {'abbr': 'vis-440',
             'code': 103,
             'title': 'VIS-440 VIS-440/Visibility at 440 nm m'},
            {'abbr': 'vis-500',
             'code': 104,
             'title': 'VIS-500 VIS-500/Visibility at 500 nm m'},
            {'abbr': 'vis-532',
             'code': 105,
             'title': 'VIS-532 VIS-532/Visibility at 532 nm m'},
            {'abbr': 'vis-675',
             'code': 106,
             'title': 'VIS-675 VIS-675/Visibility at 675 nm m'},
            {'abbr': 'vis-870',
             'code': 107,
             'title': 'VIS-870 VIS-870/Visibility at 870 nm m'},
            {'abbr': 'vis-1020',
             'code': 108,
             'title': 'VIS-1020 VIS-1020/Visibility at 1020 nm m'},
            {'abbr': 'vis-1064',
             'code': 109,
             'title': 'VIS-1064 VIS-1064/Visibility at 1064 nm m'},
            {'abbr': 'vis-3500',
             'code': 110,
             'title': 'VIS-3500 VIS-3500/Visibility at 3500 nm m'},
            {'abbr': 'vis-10000',
             'code': 111,
             'title': 'VIS-10000 VIS-10000/Visibility at 10000 nm m'},
            {'abbr': 'bsca-340',
             'code': 120,
             'title': 'BSCA-340 BSCA-340/Backscatter at 340 nm 1/m/sr'},
            {'abbr': 'bsca-355',
             'code': 121,
             'title': 'BSCA-355 BSCA-355/Backscatter at 355 nm 1/m/sr'},
            {'abbr': 'bsca-380',
             'code': 122,
             'title': 'BSCA-380 BSCA-380/Backscatter at 380 nm 1/m/sr'},
            {'abbr': 'bsca-440',
             'code': 123,
             'title': 'BSCA-440 BSCA-440/Backscatter at 440 nm 1/m/sr'},
            {'abbr': 'bsca-500',
             'code': 124,
             'title': 'BSCA-500 BSCA-500/Backscatter at 500 nm 1/m/sr'},
            {'abbr': 'bsca-532',
             'code': 125,
             'title': 'BSCA-532 BSCA-532/Backscatter at 532 nm 1/m/sr'},
            {'abbr': 'bsca-675',
             'code': 126,
             'title': 'BSCA-675 BSCA-675/Backscatter at 675 nm 1/m/sr'},
            {'abbr': 'bsca-870',
             'code': 127,
             'title': 'BSCA-870 BSCA-870/Backscatter at 870 nm 1/m/sr'},
            {'abbr': 'bsca-1020',
             'code': 128,
             'title': 'BSCA-1020 BSCA-1020/Backscatter at 1020 nm 1/m/sr'},
            {'abbr': 'bsca-1064',
             'code': 129,
             'title': 'BSCA-1064 BSCA-1064/Backscatter at 1064 nm 1/m/sr'},
            {'abbr': 'bsca-3500',
             'code': 130,
             'title': 'BSCA-3500 BSCA-3500/Backscatter at 3500 nm 1/m/sr'},
            {'abbr': 'bsca-10000',
             'code': 131,
             'title': 'BSCA-10000 BSCA-10000/Backscatter at 10000 nm 1/m/sr'},
            {'abbr': 'ext-340',
             'code': 140,
             'title': 'EXT-340 EXT-340/Extinction at 340 nm 1/m'},
            {'abbr': 'ext-355',
             'code': 141,
             'title': 'EXT-355 EXT-355/Extinction at 355 nm 1/m'},
            {'abbr': 'ext-380',
             'code': 142,
             'title': 'EXT-380 EXT-380/Extinction at 380 nm 1/m'},
            {'abbr': 'ext-440',
             'code': 143,
             'title': 'EXT-440 EXT-440/Extinction at 440 nm 1/m'},
            {'abbr': 'ext-500',
             'code': 144,
             'title': 'EXT-500 EXT-500/Extinction at 500 nm 1/m'},
            {'abbr': 'ext-532',
             'code': 145,
             'title': 'EXT-532 EXT-532/Extinction at 532 nm 1/m'},
            {'abbr': 'ext-675',
             'code': 146,
             'title': 'EXT-675 EXT-675/Extinction at 675 nm 1/m'},
            {'abbr': 'ext-870',
             'code': 147,
             'title': 'EXT-870 EXT-870/Extinction at 870 nm 1/m'},
            {'abbr': 'ext-1020',
             'code': 148,
             'title': 'EXT-1020 EXT-1020/Extinction at 1020 nm 1/m'},
            {'abbr': 'ext-1064',
             'code': 149,
             'title': 'EXT-1064 EXT-1064/Extinction at 1064 nm 1/m'},
            {'abbr': 'ext-3500',
             'code': 150,
             'title': 'EXT-3500 EXT-3500/Extinction at 3500 nm 1/m'},
            {'abbr': 'ext-10000',
             'code': 151,
             'title': 'EXT-10000 EXT-10000/Extinction at 10000 nm 1/m'},
            {'abbr': 'aod-340',
             'code': 160,
             'title': 'AOD-340 AOD-340/Aerosol optical depth at 340 nm 1'},
            {'abbr': 'aod-355',
             'code': 161,
             'title': 'AOD-355 AOD-355/Aerosol optical depth at 355 nm 1'},
            {'abbr': 'aod-380',
             'code': 162,
             'title': 'AOD-380 AOD-380/Aerosol optical depth at 380 nm 1'},
            {'abbr': 'aod-440',
             'code': 163,
             'title': 'AOD-440 AOD-440/Aerosol optical depth at 440 nm 1'},
            {'abbr': 'aod-500',
             'code': 164,
             'title': 'AOD-500 AOD-500/Aerosol optical depth at 500 nm 1'},
            {'abbr': 'aod-532',
             'code': 165,
             'title': 'AOD-532 AOD-532/Aerosol optical depth at 532 nm 1'},
            {'abbr': 'aod-675',
             'code': 166,
             'title': 'AOD-675 AOD-675/Aerosol optical depth at 675 nm 1'},
            {'abbr': 'aod-870',
             'code': 167,
             'title': 'AOD-870 AOD-870/Aerosol optical depth at 870 nm 1'},
            {'abbr': 'aod-1020',
             'code': 168,
             'title': 'AOD-1020 AOD-1020/Aerosol optical depth at 1020 nm 1'},
            {'abbr': 'aod-1064',
             'code': 169,
             'title': 'AOD-1064 AOD-1064/Aerosol optical depth at 1064 nm 1'},
            {'abbr': 'aod-3500',
             'code': 170,
             'title': 'AOD-3500 AOD-3500/Aerosol optical depth at 3500 nm 1'},
            {'abbr': 'aod-10000',
             'code': 171,
             'title': 'AOD-10000 AOD-10000/Aerosol optical depth at 10000 nm 1'},
            {'abbr': 'aod-635',
             'code': 180,
             'title': 'AOD-635 Aerosol optical thickness at 0.635 micro-m 1'},
            {'abbr': 'aod-810',
             'code': 181,
             'title': 'AOD-810 Aerosol optical thickness at 0.810 micro-m 1'},
            {'abbr': 'aod-1640',
             'code': 182,
             'title': 'AOD-1640 Aerosol optical thickness at 1.640 micro-m 1'},
            {'abbr': 'ang', 'code': 183, 'title': 'ANG Angstrom coefficient 1'},
            {'abbr': 'frain',
             'code': 208,
             'title': 'FRAIN Rain fraction of total cloud water Proportion'},
            {'abbr': 'facrain', 'code': 209, 'title': 'FACRAIN Rain factor Numeric'},
            {'abbr': 'tqr',
             'code': 210,
             'title': 'TQR Total column integrated rain kg/m2'},
            {'abbr': 'tqs',
             'code': 211,
             'title': 'TQS Total column integrated snow kg/m2'},
            {'abbr': 'twatp',
             'code': 212,
             'title': 'TWATP Total water precipitation kg/m2'},
            {'abbr': 'tsnowp',
             'code': 213,
             'title': 'TSNOWP Total snow precipitation kg/m2'},
            {'abbr': 'tcw',
             'code': 214,
             'title': 'TCW Total column water (Vertically integrated total water) kg/m2'},
            {'abbr': 'lsprate',
             'code': 215,
             'title': 'LSPRATE Large scale precipitation rate kg/m2/s'},
            {'abbr': 'csrwe',
             'code': 216,
             'title': 'CSRWE Convective snowfall rate water equivalent kg/m2/s'},
            {'abbr': 'prs_gsp',
             'code': 217,
             'title': 'PRS_GSP Large scale snowfall rate water equivalent kg/m2/s'},
            {'abbr': 'tsrate', 'code': 218, 'title': 'TSRATE Total snowfall rate m/s'},
            {'abbr': 'csrate',
             'code': 219,
             'title': 'CSRATE Convective snowfall rate m/s'},
            {'abbr': 'lssrate',
             'code': 220,
             'title': 'LSSRATE Large scale snowfall rate m/s'},
            {'abbr': 'sdwe',
             'code': 221,
             'title': 'SDWE Snow depth water equivalent kg/m2'},
            {'abbr': 'se', 'code': 222, 'title': 'SE Snow evaporation kg/m2'},
            {'abbr': 'tciwv',
             'code': 223,
             'title': 'TCIWV Total column integrated water vapour kg/m2'},
            {'abbr': 'rprate',
             'code': 224,
             'title': 'RPRATE Rain precipitation rate kg/m2/s'},
            {'abbr': 'sprate',
             'code': 225,
             'title': 'SPRATE Snow precipitation rate kg/m2/s'},
            {'abbr': 'fprate',
             'code': 226,
             'title': 'FPRATE Freezing rain precipitation rate kg/m2/s'},
            {'abbr': 'iprate',
             'code': 227,
             'title': 'IPRATE Ice pellets precipitation rate kg/m2/s'},
            {'abbr': 'clwc',
             'code': 228,
             'title': 'CLWC Specific cloud liquid water content kg/kg'},
            {'abbr': 'ciwc',
             'code': 229,
             'title': 'CIWC Specific cloud ice water content kg/kg'},
            {'abbr': 'crwc',
             'code': 230,
             'title': 'CRWC Specific rain water content kg/kg'},
            {'abbr': 'cswc',
             'code': 231,
             'title': 'CSWC Specific snow water content kg/kg'},
            {'abbr': 'ugust',
             'code': 232,
             'title': 'UGUST u-component of wind (gust) m/s'},
            {'abbr': 'vgust',
             'code': 233,
             'title': 'VGUST v-component of wind (gust) m/s'},
            {'abbr': 'vwsh', 'code': 234, 'title': 'VWSH Vertical speed shear 1/s'},
            {'abbr': 'mflx', 'code': 235, 'title': 'MFLX Horizontal momentum flux N/m2'},
            {'abbr': 'ustm', 'code': 236, 'title': 'USTM u-component storm motion m/s'},
            {'abbr': 'vstm', 'code': 237, 'title': 'VSTM v-component storm motion m/s'},
            {'abbr': 'cd', 'code': 238, 'title': 'CD Drag coefficient Numeric'},
            {'abbr': 'eta',
             'code': 239,
             'title': 'ETA Eta coordinate vertical velocity 1/s'},
            {'abbr': 'alts', 'code': 240, 'title': 'ALTS Altimeter setting Pa'},
            {'abbr': 'thick', 'code': 241, 'title': 'THICK Thickness m'},
            {'abbr': 'presalt', 'code': 242, 'title': 'PRESALT Pressure altitude m'},
            {'abbr': 'denalt', 'code': 243, 'title': 'DENALT Density altitude m'},
            {'abbr': '5wavh',
             'code': 244,
             'title': '5WAVH 5-wave geopotential height gpm'},
            {'abbr': 'u-gwd',
             'code': 245,
             'title': 'U-GWD Zonal flux of gravity wave stress N/m2'},
            {'abbr': 'v-gwd',
             'code': 246,
             'title': 'V-GWD Meridional flux of gravity wave stress N/m2'},
            {'abbr': 'hbpl',
             'code': 247,
             'title': 'HBPL Planetary boundary layer height m'},
            {'abbr': '5wava',
             'code': 248,
             'title': '5WAVA 5-wave geopotential height anomaly gpm'},
            {'abbr': 'stdsgor',
             'code': 249,
             'title': 'STDSGOR Standard deviation of sub-gridscale orography m'},
            {'abbr': 'angsgor',
             'code': 250,
             'title': 'ANGSGOR Angle of sub-gridscale orography rad'},
            {'abbr': 'slsgor',
             'code': 251,
             'title': 'SLSGOR Slope of sub-gridscale orography Numeric'},
            {'abbr': 'gwd', 'code': 252, 'title': 'GWD Gravity wave dissipation W/m2'},
            {'abbr': 'isor',
             'code': 253,
             'title': 'ISOR Anisotropy of sub-gridscale orography Numeric'},
            {'abbr': 'nlpres',
             'code': 254,
             'title': 'NLPRES Natural logarithm of pressure in Pa Numeric'})
