def load(h):
    return ({'abbr': 'sst_lake',
             'code': 11,
             'title': 'SST_LAKE Sea surface temperature (LAKE) K'},
            {'abbr': 'ecurr', 'code': 49, 'title': 'ECURR Current east m/s'},
            {'abbr': 'ncurr', 'code': 50, 'title': 'NCURR Current north m/s'},
            {'abbr': 'sd_pr', 'code': 66, 'title': 'SD_PR Snowdepth in Probe m'},
            {'abbr': 'iceconc_lake',
             'code': 91,
             'title': 'ICECONC_LAKE Ice concentration (LAKE) fraction'},
            {'abbr': 'iceth_pr',
             'code': 92,
             'title': 'ICETH_PR Ice thickness Probe-lake m'},
            {'abbr': 't_abc', 'code': 150, 'title': 'T_ABC Temperature ABC-lake K'},
            {'abbr': 't_c', 'code': 151, 'title': 'T_C Temperature C-lake K'},
            {'abbr': 't_d', 'code': 152, 'title': 'T_D Temperature D-lake K'},
            {'abbr': 't_e', 'code': 153, 'title': 'T_E Temperature E-lake K'},
            {'abbr': 'ar_abc', 'code': 160, 'title': 'AR_ABC Area ABC-lake km2'},
            {'abbr': 'dp_abc', 'code': 161, 'title': 'DP_ABC Depth ABC-lake m'},
            {'abbr': 'c', 'code': 162, 'title': 'C C-lakes amount'},
            {'abbr': 'd', 'code': 163, 'title': 'D D-lakes amount'},
            {'abbr': 'e', 'code': 164, 'title': 'E E-lakes amount'},
            {'abbr': 'iceth_abc',
             'code': 170,
             'title': 'ICETH_ABC Ice thickness ABC-lake m'},
            {'abbr': 'iceth_c', 'code': 171, 'title': 'ICETH_C Ice thickness C-lake m'},
            {'abbr': 'iceth_d', 'code': 172, 'title': 'ICETH_D Ice thickness D-lake m'},
            {'abbr': 'iceth_e', 'code': 173, 'title': 'ICETH_E Ice thickness E-lake m'},
            {'abbr': 'sst_t', 'code': 180, 'title': 'SST_T Sea surface temperature (T) K'},
            {'abbr': 'iceconc_i',
             'code': 183,
             'title': 'ICECONC_I Ice concentration (I) fraction'},
            {'abbr': 'fl', 'code': 196, 'title': 'FL Fraction lake fraction'},
            {'abbr': 'bit_pr',
             'code': 241,
             'title': 'BIT_PR Black ice thickness in Probe m'},
            {'abbr': 244, 'code': 244, 'title': 'None Vallad istjocklek i Probe m'},
            {'abbr': 'intice_pr',
             'code': 245,
             'title': 'INTICE_PR Internal ice concentration in Probe fraction'},
            {'abbr': 'icefr_pr', 'code': 246, 'title': 'ICEFR_PR Isfrontlaege i Probe m'},
            {'abbr': 'heat_pr', 'code': 250, 'title': 'HEAT_PR Heat in Probe Joule'},
            {'abbr': 'tke', 'code': 251, 'title': 'TKE Turbulent Kintetic Energy J/kg'},
            {'abbr': 'tkediss',
             'code': 252,
             'title': 'TKEDISS Dissipation rate Turbulent Kinetic Energy W/kg'})
