def load(h):
    return ({'abbr': 44,
             'code': 44,
             'title': 'CAPESI Convective available potential energy shear index',
             'units': '-1 to 1'},
            {'abbr': 45,
             'code': 45,
             'title': 'WVFI Water vapour flux index',
             'units': 'dimensionless'},
            {'abbr': 49,
             'code': 49,
             'title': '10GP 10 metre wind gust index',
             'units': '-1 to 1'},
            {'abbr': 'capei',
             'code': 59,
             'title': 'CAPEI Convective available potential energy index',
             'units': '-1 to 1'},
            {'abbr': 144, 'code': 144, 'title': 'sfi Snowfall index', 'units': '-1 to 1'},
            {'abbr': 165,
             'code': 165,
             'title': '10SP 10 metre speed index',
             'units': '-1 to 1'},
            {'abbr': 167,
             'code': 167,
             'title': '2TP 2 metre temperature index',
             'units': '-1 to 1'},
            {'abbr': 201,
             'code': 201,
             'title': 'Maximum temperature at 2 metres index',
             'units': '-1 to 1'},
            {'abbr': 202,
             'code': 202,
             'title': 'Minimum temperature at 2 metres index',
             'units': '-1 to 1'},
            {'abbr': 216,
             'code': 216,
             'title': 'Maximum of significant wave height index',
             'units': '-1 to 1'},
            {'abbr': 228,
             'code': 228,
             'title': 'TTP Total precipitation index',
             'units': '-1 to 1'},
            {'abbr': None, 'code': 255, 'title': '- Indicates a missing value'})
