def load(h):
    return ({'abbr': 1,
             'code': 1,
             'title': 'SPPT1 Random pattern 1 for sppt',
             'units': 'dimensionless'},
            {'abbr': 2,
             'code': 2,
             'title': 'SPPT2 Random pattern 2 for sppt',
             'units': 'dimensionless'},
            {'abbr': 3,
             'code': 3,
             'title': 'SPPT3 Random pattern 3 for sppt',
             'units': 'dimensionless'},
            {'abbr': 4,
             'code': 4,
             'title': 'SPPT4 Random pattern 4 for sppt',
             'units': 'dimensionless'},
            {'abbr': 5,
             'code': 5,
             'title': 'SPPT5 Random pattern 5 for sppt',
             'units': 'dimensionless'},
            {'abbr': 101,
             'code': 101,
             'title': 'SPP1 Random pattern 1 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 102,
             'code': 102,
             'title': 'SPP2 Random pattern 2 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 103,
             'code': 103,
             'title': 'SPP3 Random pattern 3 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 104,
             'code': 104,
             'title': 'SPP4 Random pattern 4 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 105,
             'code': 105,
             'title': 'SPP5 Random pattern 5 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 106,
             'code': 106,
             'title': 'SPP6 Random pattern 6 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 107,
             'code': 107,
             'title': 'SPP7 Random pattern 7 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 108,
             'code': 108,
             'title': 'SPP8 Random pattern 8 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 109,
             'code': 109,
             'title': 'SPP9 Random pattern 9 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 110,
             'code': 110,
             'title': 'SPP10 Random pattern 10 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 111,
             'code': 111,
             'title': 'SPP11 Random pattern 11 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 112,
             'code': 112,
             'title': 'SPP12 Random pattern 12 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 113,
             'code': 113,
             'title': 'SPP13 Random pattern 13 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 114,
             'code': 114,
             'title': 'SPP14 Random pattern 14 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 115,
             'code': 115,
             'title': 'SPP15 Random pattern 15 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 116,
             'code': 116,
             'title': 'SPP16 Random pattern 16 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 117,
             'code': 117,
             'title': 'SPP17 Random pattern 17 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 118,
             'code': 118,
             'title': 'SPP18 Random pattern 18 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 119,
             'code': 119,
             'title': 'SPP19 Random pattern 19 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 120,
             'code': 120,
             'title': 'SPP20 Random pattern 20 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 121,
             'code': 121,
             'title': 'SPP21 Random pattern 21 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 122,
             'code': 122,
             'title': 'SPP22 Random pattern 22 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 123,
             'code': 123,
             'title': 'SPP23 Random pattern 23 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 124,
             'code': 124,
             'title': 'SPP24 Random pattern 24 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 125,
             'code': 125,
             'title': 'SPP25 Random pattern 25 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 126,
             'code': 126,
             'title': 'SPP26 Random pattern 26 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 127,
             'code': 127,
             'title': 'SPP27 Random pattern 27 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 128,
             'code': 128,
             'title': 'SPP28 Random pattern 28 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 129,
             'code': 129,
             'title': 'SPP29 Random pattern 29 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 130,
             'code': 130,
             'title': 'SPP30 Random pattern 30 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 131,
             'code': 131,
             'title': 'SPP31 Random pattern 31 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 132,
             'code': 132,
             'title': 'SPP32 Random pattern 32 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 133,
             'code': 133,
             'title': 'SPP33 Random pattern 33 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 134,
             'code': 134,
             'title': 'SPP34 Random pattern 34 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 135,
             'code': 135,
             'title': 'SPP35 Random pattern 35 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 136,
             'code': 136,
             'title': 'SPP36 Random pattern 36 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 137,
             'code': 137,
             'title': 'SPP37 Random pattern 37 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 138,
             'code': 138,
             'title': 'SPP38 Random pattern 38 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 139,
             'code': 139,
             'title': 'SPP39 Random pattern 39 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 140,
             'code': 140,
             'title': 'SPP40 Random pattern 40 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 141,
             'code': 141,
             'title': 'SPP41 Random pattern 41 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 142,
             'code': 142,
             'title': 'SPP42 Random pattern 42 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 143,
             'code': 143,
             'title': 'SPP43 Random pattern 43 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 144,
             'code': 144,
             'title': 'SPP44 Random pattern 44 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 145,
             'code': 145,
             'title': 'SPP45 Random pattern 45 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 146,
             'code': 146,
             'title': 'SPP46 Random pattern 46 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 147,
             'code': 147,
             'title': 'SPP47 Random pattern 47 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 148,
             'code': 148,
             'title': 'SPP48 Random pattern 48 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 149,
             'code': 149,
             'title': 'SPP49 Random pattern 49 for SPP scheme',
             'units': 'dimensionless'},
            {'abbr': 150,
             'code': 150,
             'title': 'SPP50 Random pattern 50 for SPP scheme',
             'units': 'dimensionless'})
