def load(h):
    return ({'abbr': 6, 'code': 6, 'title': '- Total soil moisture', 'units': 'm'},
            {'abbr': 31,
             'code': 31,
             'title': '- Fraction of sea-ice in sea',
             'units': '0 - 1'},
            {'abbr': 34,
             'code': 34,
             'title': '- Open-sea surface temperature',
             'units': 'K'},
            {'abbr': 39,
             'code': 39,
             'title': '- Volumetric soil water layer 1',
             'units': 'm**3 m**-3'},
            {'abbr': 40,
             'code': 40,
             'title': '- Volumetric soil water layer 2',
             'units': 'm**3 m**-3'},
            {'abbr': 41,
             'code': 41,
             'title': '- Volumetric soil water layer 3',
             'units': 'm**3 m**-3'},
            {'abbr': 42,
             'code': 42,
             'title': '- Volumetric soil water layer 4',
             'units': 'm**3 m**-3'},
            {'abbr': 49,
             'code': 49,
             'title': '- 10m wind gust in the last 24 hours',
             'units': 'm s**-1'},
            {'abbr': 55,
             'code': 55,
             'title': '- 1.5m temperature - mean in the last 24 hours',
             'units': 'K'},
            {'abbr': 83,
             'code': 83,
             'title': '- Net primary productivity',
             'units': 'kg C m**-2 s**-1'},
            {'abbr': 85,
             'code': 85,
             'title': '- 10m U wind over land',
             'units': 'm s**-1'},
            {'abbr': 86,
             'code': 86,
             'title': '- 10m V wind over land',
             'units': 'm s**-1'},
            {'abbr': 87,
             'code': 87,
             'title': '- 1.5m temperature over land',
             'units': 'K'},
            {'abbr': 88,
             'code': 88,
             'title': '- 1.5m dewpoint temperature over land',
             'units': 'K'},
            {'abbr': 89,
             'code': 89,
             'title': '- Top incoming solar radiation',
             'units': 'J m**-2'},
            {'abbr': 90,
             'code': 90,
             'title': '- Top outgoing solar radiation',
             'units': 'J m**-2'},
            {'abbr': 110,
             'code': 110,
             'title': '- Ocean ice concentration',
             'units': '0 - 1'},
            {'abbr': 111, 'code': 111, 'title': '- Ocean mean ice depth', 'units': 'm'},
            {'abbr': 139,
             'code': 139,
             'title': '- Soil temperature layer 1',
             'units': 'K'},
            {'abbr': 164,
             'code': 164,
             'title': '- Average potential temperature in upper 293.4m',
             'units': 'degrees C'},
            {'abbr': 167, 'code': 167, 'title': '- 1.5m temperature', 'units': 'K'},
            {'abbr': 168,
             'code': 168,
             'title': '- 1.5m dewpoint temperature',
             'units': 'K'},
            {'abbr': 170,
             'code': 170,
             'title': '- Soil temperature layer 2',
             'units': 'K'},
            {'abbr': 172, 'code': 172, 'title': 'lsm Land-sea mask', 'units': '0 - 1'},
            {'abbr': 175,
             'code': 175,
             'title': '- Average salinity in upper 293.4m',
             'units': 'psu'},
            {'abbr': 183,
             'code': 183,
             'title': '- Soil temperature layer 3',
             'units': 'K'},
            {'abbr': 201,
             'code': 201,
             'title': '- 1.5m temperature - maximum in the last 24 hours',
             'units': 'K'},
            {'abbr': 202,
             'code': 202,
             'title': '- 1.5m temperature - minimum in the last 24 hours',
             'units': 'K'},
            {'abbr': 236,
             'code': 236,
             'title': '- Soil temperature layer 4',
             'units': 'K'},
            {'abbr': None, 'code': 255, 'title': '- Indicates a missing value'})
