def load(h):
    return ({'abbr': 129, 'code': 129, 'title': 'Z Geopotential', 'units': 'm**2 s**-2'},
            {'abbr': 130, 'code': 130, 'title': 'T Temperature', 'units': 'K'},
            {'abbr': 131,
             'code': 131,
             'title': 'U U component of wind',
             'units': 'm s**-1'},
            {'abbr': 132,
             'code': 132,
             'title': 'V V component of wind',
             'units': 'm s**-1'},
            {'abbr': 133,
             'code': 133,
             'title': 'Q Specific humidity',
             'units': 'kg kg**-1'},
            {'abbr': 134, 'code': 134, 'title': 'SP Surface pressure', 'units': 'Pa'},
            {'abbr': 137,
             'code': 137,
             'title': 'TCWV Total column water vapour',
             'units': 'kg m**-2'},
            {'abbr': 138,
             'code': 138,
             'title': 'VO Vorticity (relative)',
             'units': 's**-1'},
            {'abbr': 141,
             'code': 141,
             'title': 'SD Snow depth',
             'units': 'm of water equivalent'},
            {'abbr': 142,
             'code': 142,
             'title': 'LSP Large-scale precipitation',
             'units': 'm'},
            {'abbr': 143,
             'code': 143,
             'title': 'CP Convective precipitation',
             'units': 'm'},
            {'abbr': 144,
             'code': 144,
             'title': 'SF Snowfall',
             'units': 'm of water equivalent'},
            {'abbr': 146,
             'code': 146,
             'title': 'SSHF Surface sensible heat flux',
             'units': 'J m**-2'},
            {'abbr': 147,
             'code': 147,
             'title': 'SLHF Surface latent heat flux',
             'units': 'J m**-2'},
            {'abbr': 149, 'code': 149, 'title': 'TSW Total soil wetness', 'units': 'm'},
            {'abbr': 151,
             'code': 151,
             'title': 'MSL Mean sea level pressure',
             'units': 'Pa'},
            {'abbr': 155, 'code': 155, 'title': 'D Divergence', 'units': 's**-1'},
            {'abbr': 164, 'code': 164, 'title': 'TCC Total cloud cover', 'units': '0 - 1'},
            {'abbr': 165,
             'code': 165,
             'title': '10U 10 metre U wind component',
             'units': 'm s**-1'},
            {'abbr': 166,
             'code': 166,
             'title': '10V 10 metre V wind component',
             'units': 'm s**-1'},
            {'abbr': 167, 'code': 167, 'title': '2T 2 metre temperature', 'units': 'K'},
            {'abbr': 168,
             'code': 168,
             'title': '2D 2 metre dewpoint temperature',
             'units': 'K'},
            {'abbr': 172, 'code': 172, 'title': 'LSM Land-sea mask', 'units': '0 - 1'},
            {'abbr': 176,
             'code': 176,
             'title': 'SSR Surface net solar radiation',
             'units': 'J m**-2'},
            {'abbr': 177,
             'code': 177,
             'title': 'STR Surface net thermal radiation',
             'units': 'J m**-2'},
            {'abbr': 178,
             'code': 178,
             'title': 'TSR Top net solar radiation',
             'units': 'J m**-2'},
            {'abbr': 179,
             'code': 179,
             'title': 'TTR Top net thermal radiation',
             'units': 'J m**-2'},
            {'abbr': 180,
             'code': 180,
             'title': 'EWSS Eastward turbulent surface stress',
             'units': 'N m**-2 s'},
            {'abbr': 181,
             'code': 181,
             'title': 'NSSS Northward turbulent surface stress',
             'units': 'N m**-2 s'},
            {'abbr': 182,
             'code': 182,
             'title': 'E Evaporation',
             'units': 'm of water equivalent'},
            {'abbr': 205, 'code': 205, 'title': 'RO Runoff', 'units': 'm'},
            {'abbr': None, 'code': 255, 'title': '- Indicates a missing value'})
