def load(h):
    return ({'abbr': '2tplm10',
             'code': 1,
             'title': '2m temperature probability less than -10 C %'},
            {'abbr': '2tplm5',
             'code': 2,
             'title': '2m temperature probability less than -5 C %'},
            {'abbr': '2tpl0',
             'code': 3,
             'title': '2m temperature probability less than 0 C %'},
            {'abbr': '2tpl5',
             'code': 4,
             'title': '2m temperature probability less than 5 C %'},
            {'abbr': '2tpl10',
             'code': 5,
             'title': '2m temperature probability less than 10 C %'},
            {'abbr': '2tpg25',
             'code': 6,
             'title': '2m temperature probability greater than 25 C %'},
            {'abbr': '2tpg30',
             'code': 7,
             'title': '2m temperature probability greater than 30 C %'},
            {'abbr': '2tpg35',
             'code': 8,
             'title': '2m temperature probability greater than 35 C %'},
            {'abbr': '2tpg40',
             'code': 9,
             'title': '2m temperature probability greater than 40 C %'},
            {'abbr': '2tpg45',
             'code': 10,
             'title': '2m temperature probability greater than 45 C %'},
            {'abbr': 'mn2tplm10',
             'code': 11,
             'title': 'Minimum 2 metre temperature probability less than -10 C %'},
            {'abbr': 'mn2tplm5',
             'code': 12,
             'title': 'Minimum 2 metre temperature probability less than -5 C %'},
            {'abbr': 'mn2tpl0',
             'code': 13,
             'title': 'Minimum 2 metre temperature probability less than 0 C %'},
            {'abbr': 'mn2tpl5',
             'code': 14,
             'title': 'Minimum 2 metre temperature probability less than 5 C %'},
            {'abbr': 'mn2tpl10',
             'code': 15,
             'title': 'Minimum 2 metre temperature probability less than 10 C %'},
            {'abbr': 'mx2tpg25',
             'code': 16,
             'title': 'Maximum 2 metre temperature probability greater than 25 C %'},
            {'abbr': 'mx2tpg30',
             'code': 17,
             'title': 'Maximum 2 metre temperature probability greater than 30 C %'},
            {'abbr': 'mx2tpg35',
             'code': 18,
             'title': 'Maximum 2 metre temperature probability greater than 35 C %'},
            {'abbr': 'mx2tpg40',
             'code': 19,
             'title': 'Maximum 2 metre temperature probability greater than 40 C %'},
            {'abbr': 'mx2tpg45',
             'code': 20,
             'title': 'Maximum 2 metre temperature probability greater than 45 C %'},
            {'abbr': '10spg10',
             'code': 21,
             'title': '10 metre wind speed probability of at least 10 m/s %'},
            {'abbr': '10spg15',
             'code': 22,
             'title': '10 metre wind speed probability of at least 15 m/s %'},
            {'abbr': '10spg20',
             'code': 23,
             'title': '10 metre wind speed probability of at least 20 m/s %'},
            {'abbr': '10spg35',
             'code': 24,
             'title': '10 metre wind speed probability of at least 35 m/s %'},
            {'abbr': '10spg50',
             'code': 25,
             'title': '10 metre wind speed probability of at least 50 m/s %'},
            {'abbr': '10gpg20',
             'code': 26,
             'title': '10 metre wind gust probability of at least 20 m/s %'},
            {'abbr': '10gpg35',
             'code': 27,
             'title': '10 metre wind gust probability of at least 35 m/s %'},
            {'abbr': '10gpg50',
             'code': 28,
             'title': '10 metre wind gust probability of at least 50 m/s %'},
            {'abbr': '10gpg75',
             'code': 29,
             'title': '10 metre wind gust probability of at least 75 m/s %'},
            {'abbr': '10gpg100',
             'code': 30,
             'title': '10 metre wind gust probability of at least 100 m/s %'},
            {'abbr': 'tppg1',
             'code': 31,
             'title': 'Total precipitation probability of at least 1 mm %'},
            {'abbr': 'tppg5',
             'code': 32,
             'title': 'Total precipitation probability of at least 5 mm %'},
            {'abbr': 'tppg10',
             'code': 33,
             'title': 'Total precipitation probability of at least 10 mm %'},
            {'abbr': 'tppg20',
             'code': 34,
             'title': 'Total precipitation probability of at least 20 mm %'},
            {'abbr': 'tppg40',
             'code': 35,
             'title': 'Total precipitation probability of at least 40 mm %'},
            {'abbr': 'tppg60',
             'code': 36,
             'title': 'Total precipitation probability of at least 60 mm %'},
            {'abbr': 'tppg80',
             'code': 37,
             'title': 'Total precipitation probability of at least 80 mm %'},
            {'abbr': 'tppg100',
             'code': 38,
             'title': 'Total precipitation probability of at least 100 mm %'},
            {'abbr': 'tppg150',
             'code': 39,
             'title': 'Total precipitation probability of at least 150 mm %'},
            {'abbr': 'tppg200',
             'code': 40,
             'title': 'Total precipitation probability of at least 200 mm %'},
            {'abbr': 'tppg300',
             'code': 41,
             'title': 'Total precipitation probability of at least 300 mm %'},
            {'abbr': 'sfpg1',
             'code': 42,
             'title': 'Snowfall probability of at least 1 mm %'},
            {'abbr': 'sfpg5',
             'code': 43,
             'title': 'Snowfall probability of at least 5 mm %'},
            {'abbr': 'sfpg10',
             'code': 44,
             'title': 'Snowfall probability of at least 10 mm %'},
            {'abbr': 'sfpg20',
             'code': 45,
             'title': 'Snowfall probability of at least 20 mm %'},
            {'abbr': 'sfpg40',
             'code': 46,
             'title': 'Snowfall probability of at least 40 mm %'},
            {'abbr': 'sfpg60',
             'code': 47,
             'title': 'Snowfall probability of at least 60 mm %'},
            {'abbr': 'sfpg80',
             'code': 48,
             'title': 'Snowfall probability of at least 80 mm %'},
            {'abbr': 'sfpg100',
             'code': 49,
             'title': 'Snowfall probability of at least 100 mm %'},
            {'abbr': 'sfpg150',
             'code': 50,
             'title': 'Snowfall probability of at least 150 mm %'},
            {'abbr': 'sfpg200',
             'code': 51,
             'title': 'Snowfall probability of at least 200 mm %'},
            {'abbr': 'sfpg300',
             'code': 52,
             'title': 'Snowfall probability of at least 300 mm %'},
            {'abbr': 'tccpg10',
             'code': 53,
             'title': 'Total Cloud Cover probability greater than 10% %'},
            {'abbr': 'tccpg20',
             'code': 54,
             'title': 'Total Cloud Cover probability greater than 20% %'},
            {'abbr': 'tccpg30',
             'code': 55,
             'title': 'Total Cloud Cover probability greater than 30% %'},
            {'abbr': 'tccpg40',
             'code': 56,
             'title': 'Total Cloud Cover probability greater than 40% %'},
            {'abbr': 'tccpg50',
             'code': 57,
             'title': 'Total Cloud Cover probability greater than 50% %'},
            {'abbr': 'tccpg60',
             'code': 58,
             'title': 'Total Cloud Cover probability greater than 60% %'},
            {'abbr': 'tccpg70',
             'code': 59,
             'title': 'Total Cloud Cover probability greater than 70% %'},
            {'abbr': 'tccpg80',
             'code': 60,
             'title': 'Total Cloud Cover probability greater than 80% %'},
            {'abbr': 'tccpg90',
             'code': 61,
             'title': 'Total Cloud Cover probability greater than 90% %'},
            {'abbr': 'tccpg99',
             'code': 62,
             'title': 'Total Cloud Cover probability greater than 99% %'},
            {'abbr': 'hccpg10',
             'code': 63,
             'title': 'High Cloud Cover probability greater than 10% %'},
            {'abbr': 'hccpg20',
             'code': 64,
             'title': 'High Cloud Cover probability greater than 20% %'},
            {'abbr': 'hccpg30',
             'code': 65,
             'title': 'High Cloud Cover probability greater than 30% %'},
            {'abbr': 'hccpg40',
             'code': 66,
             'title': 'High Cloud Cover probability greater than 40% %'},
            {'abbr': 'hccpg50',
             'code': 67,
             'title': 'High Cloud Cover probability greater than 50% %'},
            {'abbr': 'hccpg60',
             'code': 68,
             'title': 'High Cloud Cover probability greater than 60% %'},
            {'abbr': 'hccpg70',
             'code': 69,
             'title': 'High Cloud Cover probability greater than 70% %'},
            {'abbr': 'hccpg80',
             'code': 70,
             'title': 'High Cloud Cover probability greater than 80% %'},
            {'abbr': 'hccpg90',
             'code': 71,
             'title': 'High Cloud Cover probability greater than 90% %'},
            {'abbr': 'hccpg99',
             'code': 72,
             'title': 'High Cloud Cover probability greater than 99% %'},
            {'abbr': 'mccpg10',
             'code': 73,
             'title': 'Medium Cloud Cover probability greater than 10% %'},
            {'abbr': 'mccpg20',
             'code': 74,
             'title': 'Medium Cloud Cover probability greater than 20% %'},
            {'abbr': 'mccpg30',
             'code': 75,
             'title': 'Medium Cloud Cover probability greater than 30% %'},
            {'abbr': 'mccpg40',
             'code': 76,
             'title': 'Medium Cloud Cover probability greater than 40% %'},
            {'abbr': 'mccpg50',
             'code': 77,
             'title': 'Medium Cloud Cover probability greater than 50% %'},
            {'abbr': 'mccpg60',
             'code': 78,
             'title': 'Medium Cloud Cover probability greater than 60% %'},
            {'abbr': 'mccpg70',
             'code': 79,
             'title': 'Medium Cloud Cover probability greater than 70% %'},
            {'abbr': 'mccpg80',
             'code': 80,
             'title': 'Medium Cloud Cover probability greater than 80% %'},
            {'abbr': 'mccpg90',
             'code': 81,
             'title': 'Medium Cloud Cover probability greater than 90% %'},
            {'abbr': 'mccpg99',
             'code': 82,
             'title': 'Medium Cloud Cover probability greater than 99% %'},
            {'abbr': 'lccpg10',
             'code': 83,
             'title': 'Low Cloud Cover probability greater than 10% %'},
            {'abbr': 'lccpg20',
             'code': 84,
             'title': 'Low Cloud Cover probability greater than 20% %'},
            {'abbr': 'lccpg30',
             'code': 85,
             'title': 'Low Cloud Cover probability greater than 30% %'},
            {'abbr': 'lccpg40',
             'code': 86,
             'title': 'Low Cloud Cover probability greater than 40% %'},
            {'abbr': 'lccpg50',
             'code': 87,
             'title': 'Low Cloud Cover probability greater than 50% %'},
            {'abbr': 'lccpg60',
             'code': 88,
             'title': 'Low Cloud Cover probability greater than 60% %'},
            {'abbr': 'lccpg70',
             'code': 89,
             'title': 'Low Cloud Cover probability greater than 70% %'},
            {'abbr': 'lccpg80',
             'code': 90,
             'title': 'Low Cloud Cover probability greater than 80% %'},
            {'abbr': 'lccpg90',
             'code': 91,
             'title': 'Low Cloud Cover probability greater than 90% %'},
            {'abbr': 'lccpg99',
             'code': 92,
             'title': 'Low Cloud Cover probability greater than 99% %'})
