def load(h):
    return ({'abbr': 'll', 'code': 0, 'title': 'Latitude/Longitude Grid'},
            {'abbr': 'mm', 'code': 1, 'title': 'Mercator Projection Grid'},
            {'abbr': 'gp', 'code': 2, 'title': 'Gnomonic Projection Grid'},
            {'abbr': 'lc', 'code': 3, 'title': 'Lambert Conformal'},
            {'abbr': 'gg', 'code': 4, 'title': 'Gaussian Latitude/Longitude Grid'},
            {'abbr': 'ps', 'code': 5, 'title': 'Polar Stereographic Projection Grid'},
            {'abbr': 6, 'code': 6, 'title': 'Universal Transverse Mercator'},
            {'abbr': 7, 'code': 7, 'title': 'Simple polyconic projection'},
            {'abbr': 8,
             'code': 8,
             'title': 'Albers equal-area, secant or tangent, conic or bi-polar'},
            {'abbr': 9, 'code': 9, 'title': "Miller's cylingrical projection"},
            {'abbr': 10, 'code': 10, 'title': 'Rotated Latitude/Longitude grid'},
            {'abbr': 'ol', 'code': 13, 'title': 'Oblique Lambert conformal'},
            {'abbr': 14, 'code': 14, 'title': 'Rotated Gaussian latitude/longitude grid'},
            {'abbr': 20, 'code': 20, 'title': 'Stretched latitude/longitude grid'},
            {'abbr': 24, 'code': 24, 'title': 'Stretched Gaussian latitude/longitude'},
            {'abbr': 30, 'code': 30, 'title': 'Stretched and rotated latitude/longitude'},
            {'abbr': 34,
             'code': 34,
             'title': 'Stretched and rotated Gaussian latitude/longitude'},
            {'abbr': 'sh', 'code': 50, 'title': 'Spherical Harmonic Coefficients'},
            {'abbr': 60, 'code': 60, 'title': 'Rotated Spherical Harmonic coefficients'},
            {'abbr': 70, 'code': 70, 'title': 'Stretched Spherical Harmonic coefficients'},
            {'abbr': 80, 'code': 80, 'title': 'Stretched and rotated Spherical Harmonic'},
            {'abbr': 'sv',
             'code': 90,
             'title': 'Space view perspective or orthographic grid'},
            {'abbr': 193, 'code': 193, 'title': 'Quasi-regular latitude/longitude'})
