import pyeccodes.accessors as _


def load(h):

    h.add(_.Constant('GRIBEXSection1Problem', (84 - _.Get('section1Length'))))
    h.add(_.Transient('localFlag', 2))
    _.Template('grib1/mars_labeling.def').load(h)
    h.alias('grib2LocalSectionPresent', 'present')
    h.add(_.Constant('grib2LocalSectionNumber', 23))
    h.add(_.Unsigned('perturbationNumber', 2))
    h.add(_.Unsigned('systemNumber', 2))
    h.add(_.Unsigned('methodNumber', 2))
    h.add(_.Unsigned('verifyingMonth', 4))
    h.add(_.Unsigned('averagingPeriod', 1))
    h.add(_.Unsigned('forecastMonth', 2))
    h.add(_.Unsigned('referenceDate', 4))
    h.add(_.Unsigned('climateDateFrom', 4))
    h.add(_.Unsigned('climateDateTo', 4))
    h.add(_.Signed('unitsDecimalScaleFactor', 1))
    h.add(_.Unsigned('thresholdIndicator', 1))
    h.add(_.Unsigned('lowerThresholdValue', 2))
    h.add(_.Unsigned('upperThresholdValue', 2))
    h.alias('local.systemNumber', 'systemNumber')
    h.alias('local.methodNumber', 'methodNumber')
    h.alias('local.verifyingMonth', 'verifyingMonth')
    h.alias('local.averagingPeriod', 'averagingPeriod')
    h.alias('local.forecastMonth', 'forecastMonth')
    h.alias('local.referenceDate', 'referenceDate')
    h.alias('local.climateDateFrom', 'climateDateFrom')
    h.alias('local.climateDateTo', 'climateDateTo')
    h.alias('local.unitsDecimalScaleFactor', 'unitsDecimalScaleFactor')
    h.alias('local.thresholdIndicator', 'thresholdIndicator')
    h.alias('local.lowerThresholdValue', 'lowerThresholdValue')
    h.alias('local.upperThresholdValue', 'upperThresholdValue')
    h.add(_.Unsigned('numberOfForecastsInEnsemble', 2))
    h.alias('totalNumber', 'numberOfForecastsInEnsemble')
    h.add(_.Pad('padding_loc23_1', 2))
    h.alias('number', 'perturbationNumber')
    h.alias('system', 'systemNumber')
    h.alias('method', 'methodNumber')
    h.alias('refdate', 'referenceDate')
