def load(h):
    return ({'abbr': 1, 'code': 1, 'title': 'MARS labelling or ensemble forecast data'},
            {'abbr': 2, 'code': 2, 'title': 'Cluster means and standard deviations'},
            {'abbr': 3, 'code': 3, 'title': 'Satellite image data'},
            {'abbr': 4, 'code': 4, 'title': 'Ocean model data'},
            {'abbr': 5, 'code': 5, 'title': 'Forecast probability data'},
            {'abbr': 6, 'code': 6, 'title': 'Surface temperature data'},
            {'abbr': 7, 'code': 7, 'title': 'Sensitivity data'},
            {'abbr': 8, 'code': 8, 'title': 'ECMWF reanalysis data'},
            {'abbr': 9, 'code': 9, 'title': 'Singular vectors and ensemble perturbations'},
            {'abbr': 10, 'code': 10, 'title': 'EPS tubes'},
            {'abbr': 11, 'code': 11, 'title': 'Supplementary data used by the analysis'},
            {'abbr': 12,
             'code': 12,
             'title': 'Seasonal forecast monthly mean data for lagged systems'},
            {'abbr': 13, 'code': 13, 'title': 'Wave 2D spectra direction and frequency'},
            {'abbr': 14, 'code': 14, 'title': 'Brightness temperature'},
            {'abbr': 15, 'code': 15, 'title': 'Seasonal forecast data'},
            {'abbr': 16, 'code': 16, 'title': 'Seasonal forecast monthly mean data'},
            {'abbr': 17, 'code': 17, 'title': 'Surface temperature or sea-ice data'},
            {'abbr': 18, 'code': 18, 'title': 'Multianalysis ensemble data'},
            {'abbr': 19, 'code': 19, 'title': 'Extreme forecast index data'},
            {'abbr': 20, 'code': 20, 'title': '4D variational increments'},
            {'abbr': 21, 'code': 21, 'title': 'Sensitive area predictions'},
            {'abbr': 22,
             'code': 22,
             'title': 'Coupled atmospheric, wave and ocean models',
             'units': 'with hindcast support'},
            {'abbr': 23,
             'code': 23,
             'title': 'Coupled atmospheric, wave and ocean means',
             'units': 'with hindcast support'},
            {'abbr': 24, 'code': 24, 'title': 'Satellite image simulation'},
            {'abbr': 25, 'code': 25, 'title': '4DVar model errors'},
            {'abbr': 26,
             'code': 26,
             'title': 'MARS labelling or ensemble forecast data',
             'units': 'with hindcast support'},
            {'abbr': 27,
             'code': 27,
             'title': 'Forecasting Systems with Variable Resolution',
             'units': 'Obsolete'},
            {'abbr': 28, 'code': 28, 'title': 'COSMO local area EPS'},
            {'abbr': 29, 'code': 29, 'title': 'COSMO clustering information'},
            {'abbr': 30,
             'code': 30,
             'title': 'Forecasting Systems with Variable Resolution'},
            {'abbr': 31, 'code': 31, 'title': 'EUROSIP products'},
            {'abbr': 32, 'code': 32, 'title': 'Cluster Scenarios'},
            {'abbr': 35, 'code': 35, 'title': 'Elaboration of ocean model products'},
            {'abbr': 36,
             'code': 36,
             'title': 'MARS labelling for long window 4Dvar system'},
            {'abbr': 37,
             'code': 37,
             'title': 'Brightness temperature for long window 4Dvar system'},
            {'abbr': 38,
             'code': 38,
             'title': '4D variational increments for long window 4Dvar system'},
            {'abbr': 39,
             'code': 39,
             'title': '4DVar model errors for long window 4Dvar system'},
            {'abbr': 40,
             'code': 40,
             'title': 'MARS labeling with domain and model',
             'units': 'for LAM'},
            {'abbr': 49, 'code': 49, 'title': '4DVar model errors for ELDA'},
            {'abbr': 50, 'code': 50, 'title': 'Member State data'},
            {'abbr': 190, 'code': 190, 'title': 'Multiple ECMWF local definitions'},
            {'abbr': 191, 'code': 191, 'title': 'Free format data descriptor data'},
            {'abbr': 192, 'code': 192, 'title': 'Multiple ECMWF local definitions'})
