def load(h):
    return ({'bit': 1,
             'on': 0,
             'title': 'Points of first row or column scan in the +i (+x) direction'},
            {'bit': 1,
             'on': 1,
             'title': 'Points of first row or column scan in the -i (-x) direction'},
            {'bit': 2,
             'on': 0,
             'title': 'Points of first row or column scan in the -j (-y) direction'},
            {'bit': 2,
             'on': 1,
             'title': 'Points of first row or column scan in the +j (+y) direction'},
            {'bit': 3,
             'on': 0,
             'title': 'Adjacent points in i (x) direction are consecutive'},
            {'bit': 3,
             'on': 1,
             'title': 'Adjacent points in j (y) direction is consecutive'},
            {'bit': 4, 'on': 0, 'title': 'All rows scan in the same direction'},
            {'bit': 4, 'on': 1, 'title': 'Adjacent rows scans in the opposite direction'},
            {'bit': 5,
             'on': 0,
             'title': 'Points within odd rows are not offset in i (x) direction'},
            {'bit': 5,
             'on': 1,
             'title': 'Points within odd rows are offset by Di/2 in i (x) direction'},
            {'bit': 6,
             'on': 0,
             'title': 'Points within even rows are not offset in i (x) direction'},
            {'bit': 6,
             'on': 1,
             'title': 'Points within even rows are offset by Di/2 in i (x) direction'},
            {'bit': 7, 'on': 0, 'title': 'Points are not offset in j (y) direction'},
            {'bit': 7, 'on': 1, 'title': 'Points are offset by Dj/2 in j (y) direction'},
            {'bit': 8,
             'on': 0,
             'title': 'Rows have Ni grid points and columns have Nj grid points'},
            {'bit': 8,
             'on': 1,
             'title': 'Rows have Ni grid points if points are not offset in i direction '
                      'Rows have Ni-1 grid points if points are offset by Di/2 in i '
                      'direction Columns have Nj grid points if points are not offset in '
                      'j direction Columns have Nj-1 grid points if points are offset by '
                      'Dj/2 in j direction'})
