def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Unweighted mean of all members'},
            {'abbr': 1, 'code': 1, 'title': 'Weighted mean of all members'},
            {'abbr': 2,
             'code': 2,
             'title': 'Standard deviation with respect to cluster mean'},
            {'abbr': 3,
             'code': 3,
             'title': 'Standard deviation with respect to cluster mean, normalized'},
            {'abbr': 4, 'code': 4, 'title': 'Spread of all members'},
            {'abbr': 5, 'code': 5, 'title': 'Large anomaly index of all members'},
            {'abbr': 6, 'code': 6, 'title': 'Unweighted mean of the cluster members'},
            {'abbr': 7,
             'code': 7,
             'title': 'Interquartile range',
             'units': 'range between the 25th and 75th quantile'},
            {'abbr': 8, 'code': 8, 'title': 'Minimum of all ensemble members'},
            {'abbr': 9, 'code': 9, 'title': 'Maximum of all ensemble members'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
