def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Reserved'},
            {'abbr': 1, 'code': 1, 'title': 'Evergreen broadleaved forest'},
            {'abbr': 2, 'code': 2, 'title': 'Deciduous broadleaved closed forest'},
            {'abbr': 3, 'code': 3, 'title': 'Deciduous broadleaved open forest'},
            {'abbr': 4, 'code': 4, 'title': 'Evergreen needle-leaf forest'},
            {'abbr': 5, 'code': 5, 'title': 'Deciduous needle-leaf forest'},
            {'abbr': 6, 'code': 6, 'title': 'Mixed leaf trees'},
            {'abbr': 7, 'code': 7, 'title': 'Freshwater flooded trees'},
            {'abbr': 8, 'code': 8, 'title': 'Saline water flooded trees'},
            {'abbr': 9, 'code': 9, 'title': 'Mosaic tree/natural vegetation'},
            {'abbr': 10, 'code': 10, 'title': 'Burnt tree cover'},
            {'abbr': 11, 'code': 11, 'title': 'Evergreen shrubs closed-open'},
            {'abbr': 12, 'code': 12, 'title': 'Deciduous shrubs closed-open'},
            {'abbr': 13, 'code': 13, 'title': 'Herbaceous vegetation closed-open'},
            {'abbr': 14, 'code': 14, 'title': 'Sparse herbaceous or grass'},
            {'abbr': 15, 'code': 15, 'title': 'Flooded shrubs or herbaceous'},
            {'abbr': 16, 'code': 16, 'title': 'Cultivated and managed areas'},
            {'abbr': 17, 'code': 17, 'title': 'Mosaic crop/tree/natural vegetation'},
            {'abbr': 18, 'code': 18, 'title': 'Mosaic crop/shrub/grass'},
            {'abbr': 19, 'code': 19, 'title': 'Bare areas'},
            {'abbr': 20, 'code': 20, 'title': 'Water'},
            {'abbr': 21, 'code': 21, 'title': 'Snow and ice'},
            {'abbr': 22, 'code': 22, 'title': 'Artificial surface'},
            {'abbr': 23, 'code': 23, 'title': 'Ocean'},
            {'abbr': 24, 'code': 24, 'title': 'Irrigated croplands'},
            {'abbr': 25, 'code': 25, 'title': 'Rainfed croplands'},
            {'abbr': 26,
             'code': 26,
             'title': 'Mosaic cropland (50-70%) - vegetation',
             'units': '20-50%'},
            {'abbr': 27,
             'code': 27,
             'title': 'Mosaic vegetation (50-70%) - cropland',
             'units': '20-50%'},
            {'abbr': 28, 'code': 28, 'title': 'Closed broadleaved evergreen forest'},
            {'abbr': 29, 'code': 29, 'title': 'Closed needle-leaved evergreen forest'},
            {'abbr': 30, 'code': 30, 'title': 'Open needle-leaved deciduous forest'},
            {'abbr': 31,
             'code': 31,
             'title': 'Mixed broadleaved and needle-leaved forest'},
            {'abbr': 32,
             'code': 32,
             'title': 'Mosaic shrubland (50-70%) - grassland',
             'units': '20-50%'},
            {'abbr': 33,
             'code': 33,
             'title': 'Mosaic grassland (50-70%) - shrubland',
             'units': '20-50%'},
            {'abbr': 34, 'code': 34, 'title': 'Closed to open shrubland'},
            {'abbr': 35, 'code': 35, 'title': 'Sparse vegetation'},
            {'abbr': 36, 'code': 36, 'title': 'Closed to open forest regularly flooded'},
            {'abbr': 37,
             'code': 37,
             'title': 'Closed forest or shrubland permanently flooded'},
            {'abbr': 38,
             'code': 38,
             'title': 'Closed to open grassland regularly flooded'},
            {'abbr': 39, 'code': 39, 'title': 'Undefined'})
