def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Flash flood guidance (Encoded as an accumulation over a floating '
                      'subinterval of time between the reference time and valid time)',
             'units': 'kg m-2'},
            {'abbr': 1,
             'code': 1,
             'title': 'Flash flood runoff (Encoded as an accumulation over a floating '
                      'subinterval of time)',
             'units': 'kg m-2'},
            {'abbr': 2,
             'code': 2,
             'title': 'Remotely-sensed snow cover',
             'units': 'Code table 4.215'},
            {'abbr': 3,
             'code': 3,
             'title': 'Elevation of snow-covered terrain',
             'units': 'Code table 4.216'},
            {'abbr': 4,
             'code': 4,
             'title': 'Snow water equivalent per cent of normal',
             'units': '%'},
            {'abbr': 5,
             'code': 5,
             'title': 'Baseflow-groundwater runoff',
             'units': 'kg m-2'},
            {'abbr': 6, 'code': 6, 'title': 'Storm surface runoff', 'units': 'kg m-2'},
            {'abbr': 7,
             'code': 7,
             'title': 'Discharge from rivers or streams',
             'units': 'm3/s'},
            {'abbr': 8,
             'code': 8,
             'title': 'Groundwater upper storage',
             'units': 'kg m-2'},
            {'abbr': 9,
             'code': 9,
             'title': 'Groundwater lower storage',
             'units': 'kg m-2'},
            {'abbr': 10,
             'code': 10,
             'title': 'Side flow into river channel',
             'units': 'm3 s-1 m-1'},
            {'abbr': 11, 'code': 11, 'title': 'River storage of water', 'units': 'm3'},
            {'abbr': 12,
             'code': 12,
             'title': 'Floodplain storage of water',
             'units': 'm3'},
            {'abbr': 13,
             'code': 13,
             'title': 'Depth of water on soil surface',
             'units': 'kg m-2'},
            {'abbr': 14,
             'code': 14,
             'title': 'Upstream accumulated precipitation',
             'units': 'kg m-2'},
            {'abbr': 15,
             'code': 15,
             'title': 'Upstream accumulated snow melt',
             'units': 'kg m-2'},
            {'abbr': 16, 'code': 16, 'title': 'Percolation rate', 'units': 'kg m-2 s-1'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
