def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Sea or inland water'},
            {'abbr': 1, 'code': 1, 'title': 'Broadleaf-evergreen trees'},
            {'abbr': 2, 'code': 2, 'title': 'Broadleaf-deciduous trees'},
            {'abbr': 3, 'code': 3, 'title': 'Broadleaf and needleleaf trees'},
            {'abbr': 4, 'code': 4, 'title': 'Needleleaf-evergreen trees'},
            {'abbr': 5, 'code': 5, 'title': 'Needleleaf-deciduous trees'},
            {'abbr': 6, 'code': 6, 'title': 'Broadleaf trees with groundcover'},
            {'abbr': 7, 'code': 7, 'title': 'Groundcover'},
            {'abbr': 8, 'code': 8, 'title': 'Broadleaf shrubs with groundcover'},
            {'abbr': 9, 'code': 9, 'title': 'Broadleaf shrubs with bare soil'},
            {'abbr': 10,
             'code': 10,
             'title': 'Dwarf trees and shrubs with groundcover',
             'units': 'tundra'},
            {'abbr': 11, 'code': 11, 'title': 'No vegetation: bare soil'},
            {'abbr': 12,
             'code': 12,
             'title': 'Broadleaf-deciduous trees with winter wheat'},
            {'abbr': 13, 'code': 13, 'title': 'Perennial land ice'})
