def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Operational products'},
            {'abbr': 1, 'code': 1, 'title': 'Operational test products'},
            {'abbr': 2, 'code': 2, 'title': 'Research products'},
            {'abbr': 3, 'code': 3, 'title': 'Re-analysis products'},
            {'abbr': 4,
             'code': 4,
             'title': 'THORPEX Interactive Grand Global Ensemble',
             'units': 'TIGGE'},
            {'abbr': 5,
             'code': 5,
             'title': 'THORPEX Interactive Grand Global Ensemble test',
             'units': 'TIGGE'},
            {'abbr': 6, 'code': 6, 'title': 'S2S operational products'},
            {'abbr': 7, 'code': 7, 'title': 'S2S test products'},
            {'abbr': 8,
             'code': 8,
             'title': 'Uncertainties in Ensembles of Regional ReAnalyses project',
             'units': 'UERRA'},
            {'abbr': 9,
             'code': 9,
             'title': 'Uncertainties in Ensembles of Regional ReAnalyses project test',
             'units': 'UERRA'},
            {'abbr': 10,
             'code': 10,
             'title': 'Copernicus regional reanalysis',
             'units': 'CARRA/CERRA'},
            {'abbr': 11,
             'code': 11,
             'title': 'Copernicus regional reanalysis test',
             'units': 'CARRA/CERRA'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
