def load(h):
    return ({'abbr': 1, 'code': 1, 'title': 'Crops, mixed farming'},
            {'abbr': 2, 'code': 2, 'title': 'Short grass'},
            {'abbr': 3, 'code': 3, 'title': 'Evergreen needleleaf trees'},
            {'abbr': 4, 'code': 4, 'title': 'Deciduous needleleaf trees'},
            {'abbr': 5, 'code': 5, 'title': 'Deciduous broadleaf trees'},
            {'abbr': 6, 'code': 6, 'title': 'Evergreen broadleaf trees'},
            {'abbr': 7, 'code': 7, 'title': 'Tall grass'},
            {'abbr': 8, 'code': 8, 'title': 'Desert'},
            {'abbr': 9, 'code': 9, 'title': 'Tundra'},
            {'abbr': 10, 'code': 10, 'title': 'Irrigated crops'},
            {'abbr': 11, 'code': 11, 'title': 'Semidesert'},
            {'abbr': 12, 'code': 12, 'title': 'Ice caps and glaciers'},
            {'abbr': 13, 'code': 13, 'title': 'Bogs and marshes'},
            {'abbr': 14, 'code': 14, 'title': 'Inland water'},
            {'abbr': 15, 'code': 15, 'title': 'Ocean'},
            {'abbr': 16, 'code': 16, 'title': 'Evergreen shrubs'},
            {'abbr': 17, 'code': 17, 'title': 'Deciduous shrubs'},
            {'abbr': 18, 'code': 18, 'title': 'Mixed forest'},
            {'abbr': 19, 'code': 19, 'title': 'Interrupted forest'},
            {'abbr': 20, 'code': 20, 'title': 'Water and land mixtures'})
