def load(h):
    return ({'abbr': 'avg', 'code': 0, 'title': 'Average'},
            {'abbr': 'accum', 'code': 1, 'title': 'Accumulation'},
            {'abbr': 'max', 'code': 2, 'title': 'Maximum'},
            {'abbr': 'min', 'code': 3, 'title': 'Minimum'},
            {'abbr': 'diff',
             'code': 4,
             'title': 'Difference',
             'units': 'value at the end of time range minus value at the beginning'},
            {'abbr': 'rms', 'code': 5, 'title': 'Root mean square'},
            {'abbr': 'sd', 'code': 6, 'title': 'Standard deviation'},
            {'abbr': 'cov',
             'code': 7,
             'title': 'Covariance',
             'units': 'temporal variance'},
            {'abbr': 8,
             'code': 8,
             'title': 'Difference',
             'units': 'value at the start of time range minus value at the end'},
            {'abbr': 'ratio', 'code': 9, 'title': 'Ratio'},
            {'abbr': 10, 'code': 10, 'title': 'Standardized anomaly'},
            {'abbr': 'missing', 'code': 255, 'title': 'Missing'})
