def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Reserved'},
            {'abbr': 1, 'code': 1, 'title': 'Sand'},
            {'abbr': 2, 'code': 2, 'title': 'Loamy sand'},
            {'abbr': 3, 'code': 3, 'title': 'Sandy loam'},
            {'abbr': 4, 'code': 4, 'title': 'Silt loam'},
            {'abbr': 5, 'code': 5, 'title': 'Organic', 'units': 'redefined'},
            {'abbr': 6, 'code': 6, 'title': 'Sandy clay loam'},
            {'abbr': 7, 'code': 7, 'title': 'Silt clay loam'},
            {'abbr': 8, 'code': 8, 'title': 'Clay loam'},
            {'abbr': 9, 'code': 9, 'title': 'Sandy clay'},
            {'abbr': 10, 'code': 10, 'title': 'Silty clay'},
            {'abbr': 11, 'code': 11, 'title': 'Clay'},
            {'abbr': 12, 'code': 12, 'title': 'Loam'},
            {'abbr': 13, 'code': 13, 'title': 'Peat'},
            {'abbr': 14, 'code': 14, 'title': 'Rock'},
            {'abbr': 15, 'code': 15, 'title': 'Ice'},
            {'abbr': 16, 'code': 16, 'title': 'Water'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
