def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Visibility', 'units': 'm'},
            {'abbr': 1, 'code': 1, 'title': 'Albedo', 'units': '%'},
            {'abbr': 2, 'code': 2, 'title': 'Thunderstorm probability', 'units': '%'},
            {'abbr': 3, 'code': 3, 'title': 'Mixed layer depth', 'units': 'm'},
            {'abbr': 4, 'code': 4, 'title': 'Volcanic ash', 'units': 'Code table 4.206'},
            {'abbr': 5, 'code': 5, 'title': 'Icing top', 'units': 'm'},
            {'abbr': 6, 'code': 6, 'title': 'Icing base', 'units': 'm'},
            {'abbr': 7, 'code': 7, 'title': 'Icing', 'units': 'Code table 4.207'},
            {'abbr': 8, 'code': 8, 'title': 'Turbulence top', 'units': 'm'},
            {'abbr': 9, 'code': 9, 'title': 'Turbulence base', 'units': 'm'},
            {'abbr': 10, 'code': 10, 'title': 'Turbulence', 'units': 'Code table 4.208'},
            {'abbr': 11, 'code': 11, 'title': 'Turbulent kinetic energy', 'units': 'J/kg'},
            {'abbr': 12,
             'code': 12,
             'title': 'Planetary boundary-layer regime',
             'units': 'Code table 4.209'},
            {'abbr': 13,
             'code': 13,
             'title': 'Contrail intensity',
             'units': 'Code table 4.210'},
            {'abbr': 14,
             'code': 14,
             'title': 'Contrail engine type',
             'units': 'Code table 4.211'},
            {'abbr': 15, 'code': 15, 'title': 'Contrail top', 'units': 'm'},
            {'abbr': 16, 'code': 16, 'title': 'Contrail base', 'units': 'm'},
            {'abbr': 17, 'code': 17, 'title': 'Maximum snow albedo', 'units': '%'},
            {'abbr': 18, 'code': 18, 'title': 'Snow free albedo', 'units': '%'},
            {'abbr': 19, 'code': 19, 'title': 'Snow albedo', 'units': '%'},
            {'abbr': 20, 'code': 20, 'title': 'Icing', 'units': '%'},
            {'abbr': 21, 'code': 21, 'title': 'In-cloud turbulence', 'units': '%'},
            {'abbr': 22, 'code': 22, 'title': 'Clear air turbulence (CAT)', 'units': '%'},
            {'abbr': 23,
             'code': 23,
             'title': 'Supercooled large droplet probability',
             'units': '%'},
            {'abbr': 24,
             'code': 24,
             'title': 'Convective turbulent kinetic energy',
             'units': 'J/kg'},
            {'abbr': 25,
             'code': 25,
             'title': 'Weather Interpretation ww (WMO)',
             'units': '-'},
            {'abbr': 26,
             'code': 26,
             'title': 'Convective outlook',
             'units': 'Code table 4.224'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
