def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Pressure', 'units': 'Pa'},
            {'abbr': 1, 'code': 1, 'title': 'Pressure reduced to MSL', 'units': 'Pa'},
            {'abbr': 2, 'code': 2, 'title': 'Pressure tendency', 'units': 'Pa/s'},
            {'abbr': 3,
             'code': 3,
             'title': 'ICAO Standard Atmosphere Reference Height',
             'units': 'm'},
            {'abbr': 4, 'code': 4, 'title': 'Geopotential', 'units': 'm2 s-2'},
            {'abbr': 5, 'code': 5, 'title': 'Geopotential height', 'units': 'gpm'},
            {'abbr': 6, 'code': 6, 'title': 'Geometric height', 'units': 'm'},
            {'abbr': 7, 'code': 7, 'title': 'Standard deviation of height', 'units': 'm'},
            {'abbr': 8, 'code': 8, 'title': 'Pressure anomaly', 'units': 'Pa'},
            {'abbr': 9, 'code': 9, 'title': 'Geopotential height anomaly', 'units': 'gpm'},
            {'abbr': 10, 'code': 10, 'title': 'Density', 'units': 'kg m-3'},
            {'abbr': 11, 'code': 11, 'title': 'Altimeter setting', 'units': 'Pa'},
            {'abbr': 12, 'code': 12, 'title': 'Thickness', 'units': 'm'},
            {'abbr': 13, 'code': 13, 'title': 'Pressure altitude', 'units': 'm'},
            {'abbr': 14, 'code': 14, 'title': 'Density altitude', 'units': 'm'},
            {'abbr': 15,
             'code': 15,
             'title': '5-wave geopotential height',
             'units': 'gpm'},
            {'abbr': 16,
             'code': 16,
             'title': 'Zonal flux of gravity wave stress',
             'units': 'N m-2'},
            {'abbr': 17,
             'code': 17,
             'title': 'Meridional flux of gravity wave stress',
             'units': 'N m-2'},
            {'abbr': 18,
             'code': 18,
             'title': 'Planetary boundary layer height',
             'units': 'm'},
            {'abbr': 19,
             'code': 19,
             'title': '5-wave geopotential height anomaly',
             'units': 'gpm'},
            {'abbr': 20,
             'code': 20,
             'title': 'Standard deviation of sub-grid scale orography',
             'units': 'm'},
            {'abbr': 21,
             'code': 21,
             'title': 'Angle of sub-gridscale orography',
             'units': 'rad'},
            {'abbr': 22,
             'code': 22,
             'title': 'Slope of sub-gridscale orography',
             'units': 'Numeric'},
            {'abbr': 23,
             'code': 23,
             'title': 'Gravity wave dissipation',
             'units': 'W m-2'},
            {'abbr': 24,
             'code': 24,
             'title': 'Anisotropy of sub-gridscale orography',
             'units': 'Numeric'},
            {'abbr': 25,
             'code': 25,
             'title': 'Natural logarithm of pressure in Pa',
             'units': 'Numeric'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
