def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Cloud ice', 'units': 'kg m-2'},
            {'abbr': 1, 'code': 1, 'title': 'Total cloud cover', 'units': '%'},
            {'abbr': 2, 'code': 2, 'title': 'Convective cloud cover', 'units': '%'},
            {'abbr': 3, 'code': 3, 'title': 'Low cloud cover', 'units': '%'},
            {'abbr': 4, 'code': 4, 'title': 'Medium cloud cover', 'units': '%'},
            {'abbr': 5, 'code': 5, 'title': 'High cloud cover', 'units': '%'},
            {'abbr': 6, 'code': 6, 'title': 'Cloud water', 'units': 'kg m-2'},
            {'abbr': 7, 'code': 7, 'title': 'Cloud amount', 'units': '%'},
            {'abbr': 8, 'code': 8, 'title': 'Cloud type', 'units': 'Code table 4.203'},
            {'abbr': 9, 'code': 9, 'title': 'Thunderstorm maximum tops', 'units': 'm'},
            {'abbr': 10,
             'code': 10,
             'title': 'Thunderstorm coverage',
             'units': 'Code table 4.204'},
            {'abbr': 11, 'code': 11, 'title': 'Cloud base', 'units': 'm'},
            {'abbr': 12, 'code': 12, 'title': 'Cloud top', 'units': 'm'},
            {'abbr': 13, 'code': 13, 'title': 'Ceiling', 'units': 'm'},
            {'abbr': 14, 'code': 14, 'title': 'Non-convective cloud cover', 'units': '%'},
            {'abbr': 15, 'code': 15, 'title': 'Cloud work function', 'units': 'J/kg'},
            {'abbr': 16,
             'code': 16,
             'title': 'Convective cloud efficiency',
             'units': 'Proportion'},
            {'abbr': 17, 'code': 17, 'title': 'Total condensate', 'units': 'kg/kg'},
            {'abbr': 18,
             'code': 18,
             'title': 'Total column-integrated cloud water',
             'units': 'kg m-2'},
            {'abbr': 19,
             'code': 19,
             'title': 'Total column-integrated cloud ice',
             'units': 'kg m-2'},
            {'abbr': 20,
             'code': 20,
             'title': 'Total column-integrated condensate',
             'units': 'kg m-2'},
            {'abbr': 21,
             'code': 21,
             'title': 'Ice fraction of total condensate',
             'units': 'Proportion'},
            {'abbr': 22, 'code': 22, 'title': 'Cloud cover', 'units': '%'},
            {'abbr': 23, 'code': 23, 'title': 'Cloud ice mixing ratio', 'units': 'kg/kg'},
            {'abbr': 24, 'code': 24, 'title': 'Sunshine', 'units': 'Numeric'},
            {'abbr': 25,
             'code': 25,
             'title': 'Horizontal extent of cumulonimbus (CB)',
             'units': '%'},
            {'abbr': 26,
             'code': 26,
             'title': 'Height of convective cloud base',
             'units': 'm'},
            {'abbr': 27,
             'code': 27,
             'title': 'Height of convective cloud top',
             'units': 'm'},
            {'abbr': 28,
             'code': 28,
             'title': 'Number concentration of cloud droplets',
             'units': '/kg'},
            {'abbr': 29,
             'code': 29,
             'title': 'Number concentration of cloud ice',
             'units': '/kg'},
            {'abbr': 30,
             'code': 30,
             'title': 'Number density of cloud droplets',
             'units': 'm-3'},
            {'abbr': 31,
             'code': 31,
             'title': 'Number density of cloud ice',
             'units': 'm-3'},
            {'abbr': 32,
             'code': 32,
             'title': 'Fraction of cloud cover',
             'units': 'Numeric'},
            {'abbr': 33, 'code': 33, 'title': 'Sunshine duration', 'units': 's'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
