def load(h):
    return ({'bit': 1, 'on': 0, 'title': 'no boustrophedonic'},
            {'bit': 1, 'on': 1, 'title': 'boustrophedonic'},
            {'bit': 2, 'on': 0, 'title': 'Reserved'},
            {'bit': 2, 'on': 1, 'title': 'Reserved'},
            {'bit': 3, 'on': 0, 'title': 'Reserved'},
            {'bit': 3, 'on': 1, 'title': 'Reserved'},
            {'bit': 4, 'on': 0, 'title': 'Reserved'},
            {'bit': 4, 'on': 1, 'title': 'Reserved'},
            {'bit': 5, 'on': 0, 'title': 'Reserved'},
            {'bit': 5, 'on': 1, 'title': 'Reserved'},
            {'bit': 6, 'on': 0, 'title': 'Reserved'},
            {'bit': 6, 'on': 1, 'title': 'Reserved'},
            {'bit': 7, 'on': 0, 'title': 'Reserved'},
            {'bit': 7, 'on': 1, 'title': 'Reserved'},
            {'bit': 8, 'on': 0, 'title': 'Reserved'},
            {'bit': 8, 'on': 1, 'title': 'Reserved'})
