def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Base spectrum width', 'units': 'm/s'},
            {'abbr': 1, 'code': 1, 'title': 'Base reflectivity', 'units': 'dB'},
            {'abbr': 2, 'code': 2, 'title': 'Base radial velocity', 'units': 'm/s'},
            {'abbr': 3,
             'code': 3,
             'title': 'Vertically integrated liquid water (VIL)',
             'units': 'kg m-2'},
            {'abbr': 4,
             'code': 4,
             'title': 'Layer-maximum base reflectivity',
             'units': 'dB'},
            {'abbr': 5, 'code': 5, 'title': 'Precipitation', 'units': 'kg m-2'},
            {'abbr': 6, 'code': 6, 'title': 'Radar spectra (1)', 'units': '-'},
            {'abbr': 7, 'code': 7, 'title': 'Radar spectra (2)', 'units': '-'},
            {'abbr': 8, 'code': 8, 'title': 'Radar spectra (3)', 'units': '-'},
            {'abbr': 9,
             'code': 9,
             'title': 'Reflectivity of cloud droplets',
             'units': 'dB'},
            {'abbr': 10, 'code': 10, 'title': 'Reflectivity of cloud ice', 'units': 'dB'},
            {'abbr': 11, 'code': 11, 'title': 'Reflectivity of snow', 'units': 'dB'},
            {'abbr': 12, 'code': 12, 'title': 'Reflectivity of rain', 'units': 'dB'},
            {'abbr': 13, 'code': 13, 'title': 'Reflectivity of graupel', 'units': 'dB'},
            {'abbr': 14, 'code': 14, 'title': 'Reflectivity of hail', 'units': 'dB'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
