def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Clear'},
            {'abbr': 1, 'code': 1, 'title': 'Cumulonimbus'},
            {'abbr': 2, 'code': 2, 'title': 'Stratus'},
            {'abbr': 3, 'code': 3, 'title': 'Stratocumulus'},
            {'abbr': 4, 'code': 4, 'title': 'Cumulus'},
            {'abbr': 5, 'code': 5, 'title': 'Altostratus'},
            {'abbr': 6, 'code': 6, 'title': 'Nimbostratus'},
            {'abbr': 7, 'code': 7, 'title': 'Altocumulus'},
            {'abbr': 8, 'code': 8, 'title': 'Cirrostratus'},
            {'abbr': 9, 'code': 9, 'title': 'Cirrocumulus'},
            {'abbr': 10, 'code': 10, 'title': 'Cirrus'},
            {'abbr': 11,
             'code': 11,
             'title': 'Cumulonimbus - ground-based fog beneath the lowest layer'},
            {'abbr': 12,
             'code': 12,
             'title': 'Stratus - ground-based fog beneath the lowest layer'},
            {'abbr': 13,
             'code': 13,
             'title': 'Stratocumulus - ground-based fog beneath the lowest layer'},
            {'abbr': 14,
             'code': 14,
             'title': 'Cumulus - ground-based fog beneath the lowest layer'},
            {'abbr': 15,
             'code': 15,
             'title': 'Altostratus - ground-based fog beneath the lowest layer'},
            {'abbr': 16,
             'code': 16,
             'title': 'Nimbostratus - ground-based fog beneath the lowest layer'},
            {'abbr': 17,
             'code': 17,
             'title': 'Altocumulus - ground-based fog beneath the lowest layer'},
            {'abbr': 18,
             'code': 18,
             'title': 'Cirrostratus - ground-based fog beneath the lowest layer'},
            {'abbr': 19,
             'code': 19,
             'title': 'Cirrocumulus - ground-based fog beneath the lowest layer'},
            {'abbr': 20,
             'code': 20,
             'title': 'Cirrus - ground-based fog beneath the lowest layer'},
            {'abbr': 191, 'code': 191, 'title': 'Unknown'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
