def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Malaria cases', 'units': 'Fraction'},
            {'abbr': 1,
             'code': 1,
             'title': 'Malaria circumsporozoite protein rate',
             'units': 'Fraction'},
            {'abbr': 2,
             'code': 2,
             'title': 'Plasmodium falciparum entomological inoculation rate',
             'units': 'Bites per day per person'},
            {'abbr': 3,
             'code': 3,
             'title': 'Human bite rate by anopheles vectors',
             'units': 'Bites per day per person'},
            {'abbr': 4, 'code': 4, 'title': 'Malaria immunity', 'units': 'Fraction'},
            {'abbr': 5,
             'code': 5,
             'title': 'Falciparum parasite rates',
             'units': 'Fraction'},
            {'abbr': 6,
             'code': 6,
             'title': 'Detectable falciparum parasite ratio (after day 10)',
             'units': 'Fraction'},
            {'abbr': 7,
             'code': 7,
             'title': 'Anopheles vector to host ratio',
             'units': 'Fraction'},
            {'abbr': 8,
             'code': 8,
             'title': 'Anopheles vector number',
             'units': 'Number m-2'},
            {'abbr': 9,
             'code': 9,
             'title': 'Fraction of malarial vector reproductive habitat',
             'units': 'Fraction'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
