def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Net short-wave radiation flux (surface)',
             'units': 'W m-2'},
            {'abbr': 1,
             'code': 1,
             'title': 'Net short-wave radiation flux (top of atmosphere)',
             'units': 'W m-2'},
            {'abbr': 2, 'code': 2, 'title': 'Short-wave radiation flux', 'units': 'W m-2'},
            {'abbr': 3, 'code': 3, 'title': 'Global radiation flux', 'units': 'W m-2'},
            {'abbr': 4, 'code': 4, 'title': 'Brightness temperature', 'units': 'K'},
            {'abbr': 5,
             'code': 5,
             'title': 'Radiance (with respect to wave number)',
             'units': 'W m-1 sr-1'},
            {'abbr': 6,
             'code': 6,
             'title': 'Radiance (with respect to wavelength)',
             'units': 'W m-3 sr-1'},
            {'abbr': 7,
             'code': 7,
             'title': 'Downward short-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 8,
             'code': 8,
             'title': 'Upward short-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 9,
             'code': 9,
             'title': 'Net short wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 10,
             'code': 10,
             'title': 'Photosynthetically active radiation',
             'units': 'W m-2'},
            {'abbr': 11,
             'code': 11,
             'title': 'Net short-wave radiation flux, clear sky',
             'units': 'W m-2'},
            {'abbr': 12, 'code': 12, 'title': 'Downward UV radiation', 'units': 'W m-2'},
            {'abbr': 13,
             'code': 13,
             'title': 'Direct short-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 14,
             'code': 14,
             'title': 'Diffuse short-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 50,
             'code': 50,
             'title': 'UV index (under clear sky)',
             'units': 'Numeric'},
            {'abbr': 51, 'code': 51, 'title': 'UV index', 'units': 'Numeric'},
            {'abbr': 52,
             'code': 52,
             'title': 'Downward short-wave radiation flux, clear sky',
             'units': 'W m-2'},
            {'abbr': 53,
             'code': 53,
             'title': 'Upward short-wave radiation flux, clear sky',
             'units': 'W m-2'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
