def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Experimental'},
            {'abbr': 1, 'code': 1, 'title': 'Version implemented on 7 November 2001'},
            {'abbr': 2, 'code': 2, 'title': 'Version implemented on 4 November 2003'},
            {'abbr': 3, 'code': 3, 'title': 'Version implemented on 2 November 2005'},
            {'abbr': 4, 'code': 4, 'title': 'Version implemented on 7 November 2007'},
            {'abbr': 5, 'code': 5, 'title': 'Version implemented on 4 November 2009'},
            {'abbr': 6, 'code': 6, 'title': 'Version implemented on 15 September 2010'},
            {'abbr': 7, 'code': 7, 'title': 'Version implemented on 4 May 2011'},
            {'abbr': 8, 'code': 8, 'title': 'Version implemented on 2 November 2011'},
            {'abbr': 9, 'code': 9, 'title': 'Version implemented on 2 May 2012'},
            {'abbr': 10, 'code': 10, 'title': 'Version implemented on 7 November 2012'},
            {'abbr': 11, 'code': 11, 'title': 'Version implemented on 8 May 2013'},
            {'abbr': 12, 'code': 12, 'title': 'Version implemented on 14 November 2013'},
            {'abbr': 13, 'code': 13, 'title': 'Version implemented on 7 May 2014'},
            {'abbr': 14, 'code': 14, 'title': 'Version implemented on 5 November 2014'},
            {'abbr': 15, 'code': 15, 'title': 'Version implemented on 6 May 2015'},
            {'abbr': 16, 'code': 16, 'title': 'Version implemented on 11 November 2015'},
            {'abbr': 17, 'code': 17, 'title': 'Version implemented on 4 May 2016'},
            {'abbr': 18, 'code': 18, 'title': 'Version implemented on 2 November 2016'},
            {'abbr': 19,
             'code': 19,
             'title': 'Pre-operational to be implemented by next amendment'},
            {'abbr': None,
             'code': 255,
             'title': 'Master tables not used. Local table entries and local templates '
                      'may use the entire range of the table, not just those sections '
                      'marked Reserved for local used.'})
