def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Clear sky probability', 'units': '%'},
            {'abbr': 1, 'code': 1, 'title': 'Cloud top temperature', 'units': 'K'},
            {'abbr': 2, 'code': 2, 'title': 'Cloud top pressure', 'units': 'Pa'},
            {'abbr': 3, 'code': 3, 'title': 'Cloud type', 'units': 'Code table 4.218'},
            {'abbr': 4, 'code': 4, 'title': 'Cloud phase', 'units': 'Code table 4.218'},
            {'abbr': 5, 'code': 5, 'title': 'Cloud optical depth', 'units': 'Numeric'},
            {'abbr': 6,
             'code': 6,
             'title': 'Cloud particle effective radius',
             'units': 'm'},
            {'abbr': 7, 'code': 7, 'title': 'Cloud liquid water path', 'units': 'kg m-2'},
            {'abbr': 8, 'code': 8, 'title': 'Cloud ice water path', 'units': 'kg m-2'},
            {'abbr': 9, 'code': 9, 'title': 'Cloud albedo', 'units': 'Numeric'},
            {'abbr': 10, 'code': 10, 'title': 'Cloud emissivity', 'units': 'Numeric'},
            {'abbr': 11,
             'code': 11,
             'title': 'Effective absorption optical depth ratio',
             'units': 'Numeric'})
