def load(h):
    return ({'abbr': 'RADAR', 'code': 2, 'title': 'RADAR 1'},
            {'abbr': 'SCATTEROMETER1', 'code': 8, 'title': 'SCATTEROMETER 1'},
            {'abbr': 'Manual_land', 'code': 11, 'title': 'Manual land station'},
            {'abbr': 'Automatic_land', 'code': 14, 'title': 'Automatic land station'},
            {'abbr': 'Ship', 'code': 21, 'title': 'Ship'},
            {'abbr': 'Ship', 'code': 22, 'title': 'Ship abbreviated'},
            {'abbr': 'Shred', 'code': 23, 'title': 'Shred'},
            {'abbr': 'Automatic_ship', 'code': 24, 'title': 'Automatic Ship'},
            {'abbr': 'Land', 'code': 32, 'title': 'LAND'},
            {'abbr': 'Ship', 'code': 33, 'title': 'SHIP'},
            {'abbr': 'Profilers', 'code': 34, 'title': 'WIND PROFILERS'},
            {'abbr': 'Land', 'code': 35, 'title': 'LAND'},
            {'abbr': 'Ship', 'code': 36, 'title': 'SHIP'},
            {'abbr': 'Mobile', 'code': 37, 'title': 'MOBILE'},
            {'abbr': 'Land_Racob', 'code': 39, 'title': 'LAND ROCOB'},
            {'abbr': 'Ship_Racob', 'code': 40, 'title': 'SHIP ROCOB'},
            {'abbr': 'Codar', 'code': 41, 'title': 'Codar'},
            {'abbr': 'Bathy', 'code': 63, 'title': 'BATHY'},
            {'abbr': 'Tesac', 'code': 64, 'title': 'TESAC'},
            {'abbr': 'SATEM_GTS', 'code': 86, 'title': 'SATEM VIA GTS'},
            {'abbr': 'Satob', 'code': 88, 'title': 'Satob'},
            {'abbr': 'High-Res_VIS_wind', 'code': 89, 'title': 'High-resolution VIS wind'},
            {'abbr': 'AMV', 'code': 90, 'title': 'AMV'},
            {'abbr': 'SCATTEROMETER2', 'code': 122, 'title': 'SCATTEROMETER 2'},
            {'abbr': 'SCATTEROMETER3', 'code': 139, 'title': 'SCATTEROMETER 3'},
            {'abbr': 'Aircraft', 'code': 141, 'title': 'Aircraft'},
            {'abbr': 'Simulated', 'code': 142, 'title': 'Simulated'},
            {'abbr': 'Amdar', 'code': 144, 'title': 'Amdar'},
            {'abbr': 'Acars', 'code': 145, 'title': 'Acars'},
            {'abbr': 'ERS_AS_DRIBU', 'code': 160, 'title': 'ERS as DRIBU'},
            {'abbr': 'DRIBU', 'code': 165, 'title': 'DRIBU'},
            {'abbr': 'DROP', 'code': 135, 'title': 'DROP'},
            {'abbr': 'SIMULATED', 'code': 137, 'title': 'SIMULATED'},
            {'abbr': 'PAOB', 'code': 180, 'title': 'PAOB'},
            {'abbr': 'High_Res_Sim_SATEM',
             'code': 184,
             'title': 'HIGH RESOLUTION SIMULATED SATEM'},
            {'abbr': 'High_Res_Sim_DWLTOVS',
             'code': 185,
             'title': 'HIGH RESOLUTION SIMULATED DWL TOVS'},
            {'abbr': 'High_Res_Sat',
             'code': 186,
             'title': 'HIGH RESOLUTION SATTELITE REPORT'},
            {'abbr': 'SST', 'code': 188, 'title': 'SST'},
            {'abbr': 'GTS_BUFR_SATEM', 'code': 200, 'title': 'GTS BUFR 250 KM SATEM'},
            {'abbr': 'GTS_BUFR_CLR_Rad',
             'code': 201,
             'title': 'GTS BUFR SATEM CLEAR RADIANCE'},
            {'abbr': 'GTS_BUFR_DATEM_RETR',
             'code': 202,
             'title': 'GTS BUFR SATEM RETRIEVED PROFILES AND CLEAR RADIANCES'},
            {'abbr': 'OZONE',
             'code': 206,
             'title': 'RETRIEVED OZONE',
             'units': 'TOTAL & PROFILES'},
            {'abbr': 'L1C_RADIANCES',
             'code': 210,
             'title': 'LEVEL 1C CALIBRATED RADIANCES'},
            {'abbr': 'RTOVS_CLR_RAD',
             'code': 211,
             'title': 'RTOVS CLEAR RADIANCES AND RETRIEVED'},
            {'abbr': 'TOVS_CLEAR_RAD',
             'code': 212,
             'title': 'TOVS CLEAR RADIANCES AND RETRIEVED'},
            {'abbr': 'AllSky_MWRAD', 'code': 215, 'title': 'SSMI/AMSRE/SSMIS/TMI'},
            {'abbr': 'COLBA', 'code': 241, 'title': 'Colba'},
            {'abbr': 'GPSRO', 'code': 250, 'title': 'GPS RADIO OCCULTATION'},
            {'abbr': 'LIMB', 'code': 251, 'title': 'LIMB RADIANCES'},
            {'abbr': 'SCATTEROMETER4', 'code': 300, 'title': 'SCATTEROMETER 4'},
            {'abbr': 'SCATTEROMETER5', 'code': 301, 'title': 'SCATTEROMETER 5'})
