def load(h):
    return ({'abbr': 'HIRS', 'code': 0, 'title': 'HIRS'},
            {'abbr': 'MSU', 'code': 1, 'title': 'MSU'},
            {'abbr': 'SSU', 'code': 2, 'title': 'SSU'},
            {'abbr': 'AMSUA', 'code': 3, 'title': 'AMSUA'},
            {'abbr': 'AMSUB', 'code': 4, 'title': 'AMSUB'},
            {'abbr': 'SSM/I', 'code': 6, 'title': 'SSM/I'},
            {'abbr': 'TMI', 'code': 9, 'title': 'TMI'},
            {'abbr': 'SSMI/S', 'code': 10, 'title': 'SSMI/S'},
            {'abbr': 'AIRS', 'code': 11, 'title': 'AIRS'},
            {'abbr': 'MHS', 'code': 15, 'title': 'MHS'},
            {'abbr': 'IASI', 'code': 16, 'title': 'IASI'},
            {'abbr': 'AMSRE', 'code': 17, 'title': 'AMSR-E'},
            {'abbr': 'ATMS', 'code': 19, 'title': 'ATMS'},
            {'abbr': 'MVIRI', 'code': 20, 'title': 'MVIRI'},
            {'abbr': 'SEVIRI', 'code': 21, 'title': 'SEVIRI'},
            {'abbr': 'GOES', 'code': 22, 'title': 'GOES Imager'},
            {'abbr': 'MTSAT-1R', 'code': 24, 'title': 'MTSAT-1R imager'},
            {'abbr': 'CrIS', 'code': 27, 'title': 'CrIS'},
            {'abbr': 'WINDSAT', 'code': 30, 'title': 'WINDSAT'},
            {'abbr': 'MWTS', 'code': 40, 'title': 'MWTS'},
            {'abbr': 'MWHS', 'code': 41, 'title': 'MWHS'},
            {'abbr': 'AMSR2', 'code': 63, 'title': 'AMSR2'},
            {'abbr': 'GPSRO', 'code': 102, 'title': 'GPSRO'},
            {'abbr': 'GOMOS', 'code': 172, 'title': 'GOMOS'},
            {'abbr': 'MERIS', 'code': 174, 'title': 'MERIS'},
            {'abbr': 'SCIAMACHY', 'code': 175, 'title': 'SCIAMACHY'},
            {'abbr': 'GRAS', 'code': 202, 'title': 'GRAS'},
            {'abbr': 'SEVIRI_O3', 'code': 207, 'title': 'SEVIRI O3'},
            {'abbr': 'GOME-2', 'code': 220, 'title': 'GOME-2'},
            {'abbr': 'MLS', 'code': 387, 'title': 'MLS'},
            {'abbr': 'OMI', 'code': 394, 'title': 'OMI'},
            {'abbr': 'TANSO', 'code': 516, 'title': 'TANSO'},
            {'abbr': 'SBUV-2', 'code': 624, 'title': 'SBUV-2'},
            {'abbr': 'AMV_WV_CLOUDY', 'code': 2000, 'title': 'AMV WV cloudy'},
            {'abbr': 'AMV_IR', 'code': 2001, 'title': 'AMV IR'},
            {'abbr': 'AMV_VIS', 'code': 2002, 'title': 'AMV VIS'},
            {'abbr': 'AMV_WVMIX', 'code': 2003, 'title': 'AMV WVMIX'},
            {'abbr': 'AMV_WV_Clear', 'code': 2005, 'title': 'AMV Water Vapor clear'},
            {'abbr': 'AMV_WV_6.2_cloudy', 'code': 2100, 'title': 'AMV WV 6.2 cloudy'},
            {'abbr': 'AMV_IR_ch1', 'code': 2101, 'title': 'AMV IR ch1'},
            {'abbr': 'AMV_VIS_ch1', 'code': 2102, 'title': 'AMV VIS ch1'},
            {'abbr': 'AMV_WV_6.2_clear', 'code': 2105, 'title': 'AMV WV_6.2 clear'},
            {'abbr': 'AMV_WV_7.3_cloudy', 'code': 2200, 'title': 'AMV WV 7.3 cloudy'},
            {'abbr': 'AMV_IR_ch2', 'code': 2201, 'title': 'AMV IR ch2'},
            {'abbr': 'AMV_VIS-2', 'code': 2202, 'title': 'AMV VIS-2'},
            {'abbr': 'AMV_WV_7.3_clear', 'code': 2205, 'title': 'AMV WV 7.3 clear'},
            {'abbr': 'AMV_WV_cloudy_ch3', 'code': 2300, 'title': 'AMV WV cloudy ch 3'},
            {'abbr': 'AMV_IR-10', 'code': 2301, 'title': 'AMV IR-10'},
            {'abbr': 'AMV_WV_clear_Ch3', 'code': 2305, 'title': 'AMV WV clear Ch3'},
            {'abbr': 'QUIKSCAT', 'code': 2350, 'title': 'QUIKSCAT'},
            {'abbr': 'SCAT', 'code': 2150, 'title': 'SCAT'},
            {'abbr': 'ASCAT', 'code': 2190, 'title': 'ASCAT'})
