def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Temperature'},
            {'abbr': 1, 'code': 1, 'title': 'Moisture'},
            {'abbr': 2, 'code': 2, 'title': 'Momentum'},
            {'abbr': 3, 'code': 3, 'title': 'Mass'},
            {'abbr': 4, 'code': 4, 'title': 'Short-wave Radiation'},
            {'abbr': 5, 'code': 5, 'title': 'Long-wave Radiation'},
            {'abbr': 6, 'code': 6, 'title': 'Cloud'},
            {'abbr': 7, 'code': 7, 'title': 'Thermodynamic Stability indices'},
            {'abbr': 8, 'code': 8, 'title': 'Kinematic Stability indices'},
            {'abbr': 9, 'code': 9, 'title': 'Temperature Probabilities'},
            {'abbr': 10, 'code': 10, 'title': 'Moisture Probabilities'},
            {'abbr': 11, 'code': 11, 'title': 'Momentum Probabilities'},
            {'abbr': 12, 'code': 12, 'title': 'Mass Probabilities'},
            {'abbr': 13, 'code': 13, 'title': 'Aerosols'},
            {'abbr': 14, 'code': 14, 'title': 'Trace gases', 'units': 'e.g., ozone, CO2'},
            {'abbr': 15, 'code': 15, 'title': 'Radar'},
            {'abbr': 16, 'code': 16, 'title': 'Forecast Radar Imagery'},
            {'abbr': 17, 'code': 17, 'title': 'Electro-dynamics'},
            {'abbr': 18, 'code': 18, 'title': 'Nuclear/radiology'},
            {'abbr': 19, 'code': 19, 'title': 'Physical atmospheric properties'},
            {'abbr': 20,
             'code': 20,
             'title': 'Atmospheric chemical or physical constituents'},
            {'abbr': 190, 'code': 190, 'title': 'CCITT IA5 string'},
            {'abbr': 191, 'code': 191, 'title': 'Miscellaneous'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
