def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Estimated precipitation', 'units': 'kg m-2'},
            {'abbr': 1,
             'code': 1,
             'title': 'Instantaneous rain rate',
             'units': 'kg m-2 s-1'},
            {'abbr': 2, 'code': 2, 'title': 'Cloud top height', 'units': 'm'},
            {'abbr': 3,
             'code': 3,
             'title': 'Cloud top height quality indicator',
             'units': 'Code table 4.219'},
            {'abbr': 4,
             'code': 4,
             'title': 'Estimated u component of wind',
             'units': 'm s-1'},
            {'abbr': 5,
             'code': 5,
             'title': 'Estimated v component of wind',
             'units': 'm s-1'},
            {'abbr': 6, 'code': 6, 'title': 'Number of pixels used', 'units': 'Numeric'},
            {'abbr': 7, 'code': 7, 'title': 'Solar zenith angle', 'units': 'Degree'},
            {'abbr': 8, 'code': 8, 'title': 'Relative azimuth angle', 'units': 'Degree'},
            {'abbr': 9,
             'code': 9,
             'title': 'Reflectance in 0.6 micron channel',
             'units': '%'},
            {'abbr': 10,
             'code': 10,
             'title': 'Reflectance in 0.8 micron channel',
             'units': '%'},
            {'abbr': 11,
             'code': 11,
             'title': 'Reflectance in 1.6 micron channel',
             'units': '%'},
            {'abbr': 12,
             'code': 12,
             'title': 'Reflectance in 3.9 micron channel',
             'units': '%'},
            {'abbr': 13, 'code': 13, 'title': 'Atmospheric divergence', 'units': 's-1'},
            {'abbr': 19, 'code': 19, 'title': 'Wind speed', 'units': 'm s-1'},
            {'abbr': 20,
             'code': 20,
             'title': 'Aerosol optical thickness at 0.635 um',
             'units': '-'},
            {'abbr': 21,
             'code': 21,
             'title': 'Aerosol optical thickness at 0.810 um',
             'units': '-'},
            {'abbr': 22,
             'code': 22,
             'title': 'Aerosol optical thickness at 1.640 um',
             'units': '-'},
            {'abbr': 23, 'code': 23, 'title': 'Angstrom coefficient', 'units': '-'},
            {'abbr': None, 'code': 255, 'title': 'Missing', 'units': '-'})
