def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Mass density (concentration)',
             'units': 'kg m-3'},
            {'abbr': 1,
             'code': 1,
             'title': 'Column-integrated mass density (see Note 1)',
             'units': 'kg m-2'},
            {'abbr': 2,
             'code': 2,
             'title': 'Mass mixing ratio (mass fraction in air)',
             'units': 'kg kg-1'},
            {'abbr': 3,
             'code': 3,
             'title': 'Atmosphere emission mass flux',
             'units': 'kg m-2 s-1'},
            {'abbr': 4,
             'code': 4,
             'title': 'Atmosphere net production mass flux',
             'units': 'kg m-2 s-1'},
            {'abbr': 5,
             'code': 5,
             'title': 'Atmosphere net production and emission mass flux',
             'units': 'kg m-2 s-1'},
            {'abbr': 6,
             'code': 6,
             'title': 'Surface dry deposition mass flux',
             'units': 'kg m-2 s-1'},
            {'abbr': 7,
             'code': 7,
             'title': 'Surface wet deposition mass flux',
             'units': 'kg m-2 s-1'},
            {'abbr': 8,
             'code': 8,
             'title': 'Atmosphere re-emission mass flux',
             'units': 'kg m-2 s-1'},
            {'abbr': 50, 'code': 50, 'title': 'Amount in atmosphere', 'units': 'mol'},
            {'abbr': 51, 'code': 51, 'title': 'Concentration in air', 'units': 'mol m-3'},
            {'abbr': 52,
             'code': 52,
             'title': 'Volume mixing ratio (fraction in air)',
             'units': 'mol mol-1'},
            {'abbr': 53,
             'code': 53,
             'title': 'Chemical gross production rate of concentration',
             'units': 'mol m-3 s-1'},
            {'abbr': 54,
             'code': 54,
             'title': 'Chemical gross destruction rate of concentration',
             'units': 'mol m-3 s-1'},
            {'abbr': 55, 'code': 55, 'title': 'Surface flux', 'units': 'mol m-2 s-1'},
            {'abbr': 56,
             'code': 56,
             'title': 'Changes of amount in atmosphere (see Note 1)',
             'units': 'mol s-1'},
            {'abbr': 57,
             'code': 57,
             'title': 'Total yearly average burden of the atmosphere',
             'units': 'mol'},
            {'abbr': 58,
             'code': 58,
             'title': 'Total yearly averaged atmospheric loss (see Note 1)',
             'units': 'mol s-1'},
            {'abbr': 100,
             'code': 100,
             'title': 'Surface area density (aerosol)',
             'units': 'm-1'},
            {'abbr': 101,
             'code': 101,
             'title': 'Atmosphere optical thickness',
             'units': 'm'},
            {'abbr': None, 'code': 255, 'title': 'Missing', 'units': '-'})
