def load(h):
    return ({'abbr': 1, 'code': 1, 'title': 'Crops Mixed Farming'},
            {'abbr': 2, 'code': 2, 'title': 'Short Grass'},
            {'abbr': 3, 'code': 3, 'title': 'Evergreen Needleleaf Trees'},
            {'abbr': 4, 'code': 4, 'title': 'Deciduous Needleleaf Trees'},
            {'abbr': 5, 'code': 5, 'title': 'Deciduous Broadleaf Trees'},
            {'abbr': 6, 'code': 6, 'title': 'Evergreen Broadleaf Trees'},
            {'abbr': 7, 'code': 7, 'title': 'Tall Grass'},
            {'abbr': 8, 'code': 8, 'title': 'Desert'},
            {'abbr': 9, 'code': 9, 'title': 'Tundra'},
            {'abbr': 10, 'code': 10, 'title': 'Irrigated Crops'},
            {'abbr': 11, 'code': 11, 'title': 'Semidesert'},
            {'abbr': 12, 'code': 12, 'title': 'Ice Caps and Glaciers'},
            {'abbr': 13, 'code': 13, 'title': 'Bogs and Marshes'},
            {'abbr': 14, 'code': 14, 'title': 'Inland Water'},
            {'abbr': 15, 'code': 15, 'title': 'Ocean'},
            {'abbr': 16, 'code': 16, 'title': 'Evergreen Shrubs'},
            {'abbr': 17, 'code': 17, 'title': 'Deciduous Shrubs'},
            {'abbr': 18, 'code': 18, 'title': 'Mixed Forest'},
            {'abbr': 19, 'code': 19, 'title': 'Interrupted Forest'},
            {'abbr': 20, 'code': 20, 'title': 'Water and Land Mixtures'})
