def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Air concentration of Caesium 137',
             'units': 'Bq m-3'},
            {'abbr': 1,
             'code': 1,
             'title': 'Air concentration of iodine 131',
             'units': 'Bq m-3'},
            {'abbr': 2,
             'code': 2,
             'title': 'Air concentration of radioactive pollutant',
             'units': 'Bq m-3'},
            {'abbr': 3,
             'code': 3,
             'title': 'Ground deposition of Caesium 137',
             'units': 'Bq m-2'},
            {'abbr': 4,
             'code': 4,
             'title': 'Ground deposition of iodine 131',
             'units': 'Bq m-2'},
            {'abbr': 5,
             'code': 5,
             'title': 'Ground deposition of radioactive pollutant',
             'units': 'Bq m-2'},
            {'abbr': 6,
             'code': 6,
             'title': 'Time-integrated air concentration of caesium pollutant',
             'units': 'Bq s m-3'},
            {'abbr': 7,
             'code': 7,
             'title': 'Time-integrated air concentration of iodine pollutant',
             'units': 'Bq s m-3'},
            {'abbr': 8,
             'code': 8,
             'title': 'Time-integrated air concentration of radioactive pollutant',
             'units': 'Bq s m-3'},
            {'abbr': 9, 'code': 9, 'title': 'Reserved'},
            {'abbr': 10, 'code': 10, 'title': 'Air concentration', 'units': 'Bq m-3'},
            {'abbr': 11, 'code': 11, 'title': 'Wet deposition', 'units': 'Bq m-2'},
            {'abbr': 12, 'code': 12, 'title': 'Dry deposition', 'units': 'Bq m-2'},
            {'abbr': 13,
             'code': 13,
             'title': 'Total deposition (wet + dry)',
             'units': 'Bq m-2'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
