def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Latitude/longitude. Also called equidistant cylindrical, or Plate '
                      'Carree'},
            {'abbr': 1, 'code': 1, 'title': 'Rotated latitude/longitude'},
            {'abbr': 2, 'code': 2, 'title': 'Stretched latitude/longitude'},
            {'abbr': 3, 'code': 3, 'title': 'Stretched and rotated latitude/longitude'},
            {'abbr': 10, 'code': 10, 'title': 'Mercator'},
            {'abbr': 20,
             'code': 20,
             'title': 'Polar stereographic projection',
             'units': 'Can be south or north'},
            {'abbr': 30,
             'code': 30,
             'title': 'Lambert conformal',
             'units': 'Can be secant or tangent, conical or bipolar'},
            {'abbr': 31, 'code': 31, 'title': 'Albers equal area'},
            {'abbr': 40, 'code': 40, 'title': 'Gaussian latitude/longitude'},
            {'abbr': 41, 'code': 41, 'title': 'Rotated Gaussian latitude/longitude'},
            {'abbr': 42, 'code': 42, 'title': 'Stretched Gaussian latitude/longitude'},
            {'abbr': 43,
             'code': 43,
             'title': 'Stretched and rotated Gaussian latitude/longitude'},
            {'abbr': 50, 'code': 50, 'title': 'Spherical harmonic coefficients'},
            {'abbr': 51, 'code': 51, 'title': 'Rotated spherical harmonic coefficients'},
            {'abbr': 52, 'code': 52, 'title': 'Stretched spherical harmonic coefficients'},
            {'abbr': 53,
             'code': 53,
             'title': 'Stretched and rotated spherical harmonic coefficients'},
            {'abbr': 90, 'code': 90, 'title': 'Space view perspective or orthographic'},
            {'abbr': 100, 'code': 100, 'title': 'Triangular grid based on an icosahedron'},
            {'abbr': 110,
             'code': 110,
             'title': 'Equatorial azimuthal equidistant projection'},
            {'abbr': 120, 'code': 120, 'title': 'Azimuth-range projection'},
            {'abbr': 130, 'code': 130, 'title': 'Irregular latitude/longitude grid'},
            {'abbr': 140, 'code': 140, 'title': 'Lambert azimuthal equal area projection'},
            {'abbr': 1000,
             'code': 1000,
             'title': 'Cross-section grid, with points equally spaced on the horizontal'},
            {'abbr': 1100,
             'code': 1100,
             'title': 'Hovmoller diagram grid, with points equally spaced on the '
                      'horizontal'},
            {'abbr': 1200, 'code': 1200, 'title': 'Time section grid'},
            {'abbr': 65535, 'code': 65535, 'title': 'Missing'})
