def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Main thermocline depth', 'units': 'm'},
            {'abbr': 1, 'code': 1, 'title': 'Main thermocline anomaly', 'units': 'm'},
            {'abbr': 2, 'code': 2, 'title': 'Transient thermocline depth', 'units': 'm'},
            {'abbr': 3, 'code': 3, 'title': 'Salinity', 'units': 'kg kg-1'},
            {'abbr': 4,
             'code': 4,
             'title': 'Ocean vertical heat diffusivity',
             'units': 'm2 s-1'},
            {'abbr': 5,
             'code': 5,
             'title': 'Ocean vertical salt diffusivity',
             'units': 'm2 s-1'},
            {'abbr': 6,
             'code': 6,
             'title': 'Ocean vertical momentum diffusivity',
             'units': 'm2 s-1'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
