def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Grid point data - simple packing'},
            {'abbr': 1, 'code': 1, 'title': 'Matrix value - simple packing'},
            {'abbr': 2, 'code': 2, 'title': 'Grid point data - complex packing'},
            {'abbr': 3,
             'code': 3,
             'title': 'Grid point data - complex packing and spatial differencing'},
            {'abbr': 4, 'code': 4, 'title': 'Grid point data - ieee packing'},
            {'abbr': 6,
             'code': 6,
             'title': 'Grid point data - simple packing with pre-processing'},
            {'abbr': 40, 'code': 40, 'title': 'JPEG2000 Packing'},
            {'abbr': 41, 'code': 41, 'title': 'PNG pacling'},
            {'abbr': 50, 'code': 50, 'title': 'Spectral data -simple packing'},
            {'abbr': 51,
             'code': 51,
             'title': 'Spherical harmonics data - complex packing'},
            {'abbr': 61,
             'code': 61,
             'title': 'Grid point data - simple packing with logarithm pre-processing'},
            {'abbr': None, 'code': 255, 'title': 'Missing'},
            {'abbr': 40000, 'code': 40000, 'title': 'JPEG2000 Packing'},
            {'abbr': 40010, 'code': 40010, 'title': 'PNG pacling'},
            {'abbr': 50000, 'code': 50000, 'title': 'Sperical harmonics ieee packing'},
            {'abbr': 50001, 'code': 50001, 'title': 'Second order packing'},
            {'abbr': 50002, 'code': 50002, 'title': 'Second order packing'})
