def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'No scene identified'},
            {'abbr': 1, 'code': 1, 'title': 'Green needle-leafed forest'},
            {'abbr': 2, 'code': 2, 'title': 'Green broad-leafed forest'},
            {'abbr': 3, 'code': 3, 'title': 'Deciduous needle-leafed forest'},
            {'abbr': 4, 'code': 4, 'title': 'Deciduous broad-leafed forest'},
            {'abbr': 5, 'code': 5, 'title': 'Deciduous mixed forest'},
            {'abbr': 6, 'code': 6, 'title': 'Closed shrub-land'},
            {'abbr': 7, 'code': 7, 'title': 'Open shrub-land'},
            {'abbr': 8, 'code': 8, 'title': 'Woody savannah'},
            {'abbr': 9, 'code': 9, 'title': 'Savannah'},
            {'abbr': 10, 'code': 10, 'title': 'Grassland'},
            {'abbr': 11, 'code': 11, 'title': 'Permanent wetland'},
            {'abbr': 12, 'code': 12, 'title': 'Cropland'},
            {'abbr': 13, 'code': 13, 'title': 'Urban'},
            {'abbr': 14, 'code': 14, 'title': 'Vegetation/crops'},
            {'abbr': 15, 'code': 15, 'title': 'Permanent snow/ice'},
            {'abbr': 16, 'code': 16, 'title': 'Barren desert'},
            {'abbr': 17, 'code': 17, 'title': 'Water bodies'},
            {'abbr': 18, 'code': 18, 'title': 'Tundra'},
            {'abbr': 19, 'code': 19, 'title': 'Warm liquid water cloud'},
            {'abbr': 20, 'code': 20, 'title': 'Supercooled liquid water cloud'},
            {'abbr': 21, 'code': 21, 'title': 'Mixed-phase cloud'},
            {'abbr': 22, 'code': 22, 'title': 'Optically thin ice cloud'},
            {'abbr': 23, 'code': 23, 'title': 'Optically thick ice cloud'},
            {'abbr': 24, 'code': 24, 'title': 'Multilayered cloud'},
            {'abbr': 97, 'code': 97, 'title': 'Snow/ice on land'},
            {'abbr': 98, 'code': 98, 'title': 'Snow/ice on water'},
            {'abbr': 99, 'code': 99, 'title': 'Sun-glint'},
            {'abbr': 100, 'code': 100, 'title': 'General cloud'},
            {'abbr': 101, 'code': 101, 'title': 'Low cloud/fog/Stratus'},
            {'abbr': 102, 'code': 102, 'title': 'Low cloud/Stratocumulus'},
            {'abbr': 103, 'code': 103, 'title': 'Low cloud/unknown type'},
            {'abbr': 104, 'code': 104, 'title': 'Medium cloud/Nimbostratus'},
            {'abbr': 105, 'code': 105, 'title': 'Medium cloud/Altostratus'},
            {'abbr': 106, 'code': 106, 'title': 'Medium cloud/unknown type'},
            {'abbr': 107, 'code': 107, 'title': 'High cloud/Cumulus'},
            {'abbr': 108, 'code': 108, 'title': 'High cloud/Cirrus'},
            {'abbr': 109, 'code': 109, 'title': 'High cloud/unknown'},
            {'abbr': 110, 'code': 110, 'title': 'Unknown cloud type'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
