def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Interface sea-surface temperature',
             'units': 'K'},
            {'abbr': 1, 'code': 1, 'title': 'Skin sea-surface temperature', 'units': 'K'},
            {'abbr': 2,
             'code': 2,
             'title': 'Sub-skin sea-surface temperature',
             'units': 'K'},
            {'abbr': 3,
             'code': 3,
             'title': 'Foundation sea-surface temperature',
             'units': 'K'},
            {'abbr': 4,
             'code': 4,
             'title': 'Estimated bias between sea-surface temperature and standard',
             'units': 'K'},
            {'abbr': 5,
             'code': 5,
             'title': 'Estimated standard deviation between sea surface temperature and '
                      'standard',
             'units': 'K'})
