def load(h):
    return ({'abbr': 20, 'code': 20, 'title': 'Temperature K'},
            {'abbr': 100, 'code': 100, 'title': 'Pressure Pa'},
            {'abbr': 101,
             'code': 101,
             'title': 'Pressure deviation from mean sea level Pa'},
            {'abbr': 102, 'code': 102, 'title': 'Altitude above mean sea level m'},
            {'abbr': 103, 'code': 103, 'title': 'Height above ground m'},
            {'abbr': 104, 'code': 104, 'title': 'Sigma coordinate'},
            {'abbr': 105, 'code': 105, 'title': 'Hybrid coordinate'},
            {'abbr': 106, 'code': 106, 'title': 'Depth below land surface m'},
            {'abbr': 'pt', 'code': 107, 'title': 'Potential temperature (theta) K'},
            {'abbr': 108,
             'code': 108,
             'title': 'Pressure deviation from ground to level Pa'},
            {'abbr': 'pv', 'code': 109, 'title': 'Potential vorticity K m-2 kg-1 s-1'},
            {'abbr': 110, 'code': 110, 'title': 'Geometrical height m'},
            {'abbr': 111, 'code': 111, 'title': 'Eta coordinate'},
            {'abbr': 112, 'code': 112, 'title': 'Geopotential height gpm'},
            {'abbr': 160, 'code': 160, 'title': 'Depth below sea level m'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
