def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Soil type', 'units': 'Code table 4.213'},
            {'abbr': 1, 'code': 1, 'title': 'Upper layer soil temperature', 'units': 'K'},
            {'abbr': 2,
             'code': 2,
             'title': 'Upper layer soil moisture',
             'units': 'kg m-3'},
            {'abbr': 3,
             'code': 3,
             'title': 'Lower layer soil moisture',
             'units': 'kg m-3'},
            {'abbr': 4, 'code': 4, 'title': 'Bottom layer soil temperature', 'units': 'K'},
            {'abbr': 5,
             'code': 5,
             'title': 'Liquid volumetric soil moisture (non-frozen)',
             'units': 'Proportion'},
            {'abbr': 6,
             'code': 6,
             'title': 'Number of soil layers in root zone',
             'units': 'Numeric'},
            {'abbr': 7,
             'code': 7,
             'title': 'Transpiration stress-onset (soil moisture)',
             'units': 'Proportion'},
            {'abbr': 8,
             'code': 8,
             'title': 'Direct evaporation cease (soil moisture)',
             'units': 'Proportion'},
            {'abbr': 9, 'code': 9, 'title': 'Soil porosity', 'units': 'Proportion'},
            {'abbr': 12,
             'code': 12,
             'title': 'Transpiration stress-onset (soil moisture)',
             'units': 'kg m-3'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
