def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Air concentration of Caesium 137',
             'units': 'Bq m-3'},
            {'abbr': 1,
             'code': 1,
             'title': 'Air concentration of Iodine 131',
             'units': 'Bq m-3'},
            {'abbr': 2,
             'code': 2,
             'title': 'Air concentration of radioactive pollutant',
             'units': 'Bq m-3'},
            {'abbr': 3,
             'code': 3,
             'title': 'Ground deposition of Caesium 137',
             'units': 'Bq m-2'},
            {'abbr': 4,
             'code': 4,
             'title': 'Ground deposition of Iodine 131',
             'units': 'Bq m-2'},
            {'abbr': 5,
             'code': 5,
             'title': 'Ground deposition of radioactive pollutant',
             'units': 'Bq m-2'},
            {'abbr': 6,
             'code': 6,
             'title': 'Time-integrated air concentration of caesium pollutant',
             'units': 'Bq s m-3'},
            {'abbr': 7,
             'code': 7,
             'title': 'Time-integrated air concentration of iodine pollutant',
             'units': 'Bq s m-3'},
            {'abbr': 8,
             'code': 8,
             'title': 'Time-integrated air concentration of radioactive pollutant',
             'units': 'Bq s m-3'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
