def load(h):
    return ({'bit': 1,
             'on': 0,
             'title': 'Points scan in +i direction, i.e. from pole to equator'},
            {'bit': 1,
             'on': 1,
             'title': 'Points scan in -i direction, i.e. from equator to pole'},
            {'bit': 2,
             'on': 0,
             'title': 'Points scan in +j direction, i.e. from west to east'},
            {'bit': 2,
             'on': 1,
             'title': 'Points scan in -j direction, i.e. from east to west'},
            {'bit': 3, 'on': 0, 'title': 'Adjacent points in i direction are consecutive'},
            {'bit': 3, 'on': 1, 'title': 'Adjacent points in j direction is consecutive'})
