def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Net long wave radiation flux (surface)',
             'units': 'W m-2'},
            {'abbr': 1,
             'code': 1,
             'title': 'Net long wave radiation flux (top of atmosphere)',
             'units': 'W m-2'},
            {'abbr': 2, 'code': 2, 'title': 'Long wave radiation flux', 'units': 'W m-2'},
            {'abbr': 3,
             'code': 3,
             'title': 'Downward long-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 4,
             'code': 4,
             'title': 'Upward long-wave radiation flux',
             'units': 'W m-2'},
            {'abbr': 5,
             'code': 5,
             'title': 'Net long wave radiation flux',
             'units': 'W m-2'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
