def load(h):
    return ({'abbr': 'none', 'code': 0, 'title': 'not set, default'},
            {'abbr': 'oper',
             'code': 1025,
             'title': 'Operational deterministic model daily archive'},
            {'abbr': 'mnth', 'code': 1043, 'title': 'Monthly means'},
            {'abbr': 'moda', 'code': 1071, 'title': 'Monthly means of daily means'},
            {'abbr': 'mdfa',
             'code': 1075,
             'title': 'Monthly means of daily forecast accumulations'},
            {'abbr': 'dame', 'code': 4000, 'title': 'Daily Means'},
            {'abbr': 'seme', 'code': 4001, 'title': 'Seasonal Means'},
            {'abbr': 'secy', 'code': 4002, 'title': 'Seasonal Daily Cycle'},
            {'abbr': 'expr', 'code': 8200, 'title': 'Research Experiment'},
            {'abbr': 'rean', 'code': 8299, 'title': 'Reanalysis datasets'},
            {'abbr': 'publ', 'code': 9999, 'title': 'public data'})
