def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'All surfaces'},
            {'abbr': 1, 'code': 1, 'title': 'Water or Sea Water', 'units': 'fraction'},
            {'abbr': 2, 'code': 2, 'title': 'Rural', 'units': 'fraction'},
            {'abbr': 3, 'code': 3, 'title': 'Urban', 'units': 'fraction'},
            {'abbr': 4, 'code': 4, 'title': 'Lowveg', 'units': 'fraction'},
            {'abbr': 5, 'code': 5, 'title': 'Forest', 'units': 'fraction'},
            {'abbr': 6, 'code': 6, 'title': 'Noveg', 'units': 'fraction'},
            {'abbr': 21, 'code': 21, 'title': 'Pasture', 'units': 'fraction'},
            {'abbr': 22, 'code': 22, 'title': 'Arable', 'units': 'fraction'},
            {'abbr': 23, 'code': 23, 'title': 'Beech_oak', 'units': 'fraction'},
            {'abbr': 24, 'code': 24, 'title': 'Deciduous', 'units': 'fraction'},
            {'abbr': 25, 'code': 25, 'title': 'Spruce', 'units': 'fraction'},
            {'abbr': 26, 'code': 26, 'title': 'Pine', 'units': 'fraction'},
            {'abbr': 27, 'code': 27, 'title': 'Wetland', 'units': 'fraction'},
            {'abbr': 28, 'code': 28, 'title': 'Mountain', 'units': 'fraction'},
            {'abbr': 29, 'code': 29, 'title': 'Birch', 'units': 'fraction'},
            {'abbr': 51, 'code': 51, 'title': 'Ice', 'units': 'fraction'},
            {'abbr': 52, 'code': 52, 'title': 'Snow', 'units': 'fraction'},
            {'abbr': 71, 'code': 71, 'title': 'Hendersen-Sellers classification'},
            {'abbr': 72, 'code': 72, 'title': 'Hendersen-Sellers classification'},
            {'abbr': 73, 'code': 73, 'title': 'Politi'},
            {'abbr': 74, 'code': 74, 'title': 'Mask'},
            {'abbr': 81, 'code': 81, 'title': 'Regional contribution'},
            {'abbr': 82, 'code': 82, 'title': 'Long-range contribution'},
            {'abbr': 83, 'code': 83, 'title': 'Local (urban) contribution'},
            {'abbr': 90, 'code': 90, 'title': 'Zone index'},
            {'abbr': 100, 'code': 100, 'title': 'Top layer'},
            {'abbr': 150, 'code': 150, 'title': 'Effective dose [Sv]'},
            {'abbr': 151, 'code': 151, 'title': 'Skin dose [Sv]'},
            {'abbr': 152, 'code': 152, 'title': 'Thyroid dose [Sv]'},
            {'abbr': 153, 'code': 153, 'title': 'Lung dose [Sv]'},
            {'abbr': None, 'code': 255, 'title': 'missing value'})
