def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'No representation specified'},
            {'abbr': 1, 'code': 1, 'title': '3 Hour mean value', 'units': 'hours'},
            {'abbr': 2, 'code': 2, 'title': 'Diurnal or Daily mean', 'units': 'hours'},
            {'abbr': 3, 'code': 3, 'title': '1 Hour mean value', 'units': 'hours'},
            {'abbr': 5, 'code': 5, 'title': 'Monthly mean', 'units': 'month'},
            {'abbr': 6, 'code': 6, 'title': 'Mean from start', 'units': 'hours'},
            {'abbr': 7, 'code': 7, 'title': 'Annual mean', 'units': 'year'},
            {'abbr': 10, 'code': 10, 'title': 'Max value'},
            {'abbr': 11, 'code': 11, 'title': 'Min value'},
            {'abbr': 12, 'code': 12, 'title': 'Diurnal max'},
            {'abbr': 14, 'code': 14, 'title': 'Monthly max'},
            {'abbr': 16, 'code': 16, 'title': 'Annual max'},
            {'abbr': 17, 'code': 17, 'title': 'Mean of daily-max'},
            {'abbr': 18, 'code': 18, 'title': 'Mean of daily-max'},
            {'abbr': 19, 'code': 19, 'title': 'Mean of daily-max'},
            {'abbr': 20, 'code': 20, 'title': 'Acc. since start', 'units': 'hours'},
            {'abbr': 21, 'code': 21, 'title': 'Acc. over one day', 'units': 'hours'},
            {'abbr': 22, 'code': 22, 'title': 'Acc. over one month', 'units': 'months'},
            {'abbr': 23, 'code': 23, 'title': 'Acc. over one day', 'units': 'hours'},
            {'abbr': 24, 'code': 24, 'title': 'Acc. over three months', 'units': 'months'},
            {'abbr': 25, 'code': 25, 'title': 'Acc. over six months', 'units': 'months'},
            {'abbr': 26, 'code': 26, 'title': 'Acc. over one year', 'units': 'year'},
            {'abbr': 30, 'code': 30, 'title': 'Running 8-hour mean', 'units': 'hours'},
            {'abbr': 31, 'code': 31, 'title': 'Daily maximum of 8-hour mean'},
            {'abbr': 32, 'code': 32, 'title': 'Mean of daily maximum of 8-hour mean'},
            {'abbr': 33, 'code': 33, 'title': 'Max of daily maximum of 8-hour mean'},
            {'abbr': 40, 'code': 40, 'title': '98 percentil', 'units': 'hours'},
            {'abbr': 41, 'code': 41, 'title': '98 percentil', 'units': 'day'},
            {'abbr': 42, 'code': 42, 'title': '90 percentil', 'units': 'day'},
            {'abbr': 43, 'code': 43, 'title': 'Median'},
            {'abbr': 44, 'code': 44, 'title': 'Likelihood'},
            {'abbr': 45, 'code': 45, 'title': 'Joint probability'},
            {'abbr': 46, 'code': 46, 'title': 'Percentile'},
            {'abbr': 50, 'code': 50, 'title': 'Boundary value'},
            {'abbr': 51, 'code': 51, 'title': 'First guess'},
            {'abbr': 52, 'code': 52, 'title': 'Standard deviation'},
            {'abbr': 'ANAINCR', 'code': 60, 'title': 'Analysis increment'},
            {'abbr': 'ANAERR', 'code': 61, 'title': 'Analysis error'},
            {'abbr': 'BGERR', 'code': 62, 'title': 'Background error'},
            {'abbr': 'QUALITY', 'code': 70, 'title': 'Quality flag'},
            {'abbr': None, 'code': 255, 'title': 'missing value'})
