def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Estimated precipitation', 'units': 'kg m-2'},
            {'abbr': 1,
             'code': 1,
             'title': 'Instantaneous rain rate',
             'units': 'kg m-2 s-1'},
            {'abbr': 2, 'code': 2, 'title': 'Cloud top height', 'units': 'm'},
            {'abbr': 3,
             'code': 3,
             'title': 'Cloud top height quality indicator',
             'units': 'Code table 4.219'},
            {'abbr': 4,
             'code': 4,
             'title': 'Estimated u component of wind',
             'units': 'm s-1'},
            {'abbr': 5,
             'code': 5,
             'title': 'Estimated v component of wind',
             'units': 'm s-1'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
