def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Mass density (concentration) kg.m-3'},
            {'abbr': 1,
             'code': 1,
             'title': 'Total column (integrated mass density) kg.m-2'},
            {'abbr': 2,
             'code': 2,
             'title': 'Volume mixing ratio (mole fraction in air) mole.mole-1'},
            {'abbr': 3,
             'code': 3,
             'title': 'Mass mixing ratio (mass fraction in air) kg.kg-1'},
            {'abbr': 4, 'code': 4, 'title': 'Surface dry deposition mass flux kg.m-2.s-1'},
            {'abbr': 5, 'code': 5, 'title': 'Surface wet deposition mass flux kg.m-2.s-1'},
            {'abbr': 6, 'code': 6, 'title': 'Atmosphere emission mass flux kg.m-2.s-1'},
            {'abbr': 7,
             'code': 7,
             'title': 'Chemical gross production rate of mole concentration mole.m-3.s-1'},
            {'abbr': 8,
             'code': 8,
             'title': 'Chemical gross destruction rate of mole concentration '
                      'mole.m-3.s-1'},
            {'abbr': 9,
             'code': 9,
             'title': 'Surface dry deposition mass flux into stomata kg.m-2.s-1'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
