def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Wave spectra (1)', 'units': '-'},
            {'abbr': 1, 'code': 1, 'title': 'Wave spectra (2)', 'units': '-'},
            {'abbr': 2, 'code': 2, 'title': 'Wave spectra (3)', 'units': '-'},
            {'abbr': 3,
             'code': 3,
             'title': 'Significant height of combined wind waves and swell',
             'units': 'm'},
            {'abbr': 4,
             'code': 4,
             'title': 'Direction of wind waves',
             'units': 'Degree true'},
            {'abbr': 5,
             'code': 5,
             'title': 'Significant height of wind waves',
             'units': 'm'},
            {'abbr': 6, 'code': 6, 'title': 'Mean period of wind waves', 'units': 's'},
            {'abbr': 7,
             'code': 7,
             'title': 'Direction of swell waves',
             'units': 'Degree true'},
            {'abbr': 8,
             'code': 8,
             'title': 'Significant height of swell waves',
             'units': 'm'},
            {'abbr': 9, 'code': 9, 'title': 'Mean period of swell waves', 'units': 's'},
            {'abbr': 10,
             'code': 10,
             'title': 'Primary wave direction',
             'units': 'Degree true'},
            {'abbr': 11, 'code': 11, 'title': 'Primary wave mean period', 'units': 's'},
            {'abbr': 12,
             'code': 12,
             'title': 'Secondary wave direction',
             'units': 'Degree true'},
            {'abbr': 13, 'code': 13, 'title': 'Secondary wave mean period', 'units': 's'},
            {'abbr': None, 'code': 255, 'title': 'Missing', 'units': '-'})
