def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Ice cover', 'units': 'Proportion'},
            {'abbr': 1, 'code': 1, 'title': 'Ice thickness', 'units': 'm'},
            {'abbr': 2,
             'code': 2,
             'title': 'Direction of ice drift',
             'units': 'degree true'},
            {'abbr': 3, 'code': 3, 'title': 'Speed of ice drift', 'units': 'm/s'},
            {'abbr': 4, 'code': 4, 'title': 'u-component of ice drift', 'units': 'm/s'},
            {'abbr': 5, 'code': 5, 'title': 'v-component of ice drift', 'units': 'm/s'},
            {'abbr': 6, 'code': 6, 'title': 'Ice growth rate', 'units': 'm/s'},
            {'abbr': 7, 'code': 7, 'title': 'Ice divergence', 'units': '/s'},
            {'abbr': 8, 'code': 8, 'title': 'Ice temperature', 'units': 'K'},
            {'abbr': 9, 'code': 9, 'title': 'Ice internal pressure', 'units': 'Pa m'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
