def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Temperature', 'units': 'K'},
            {'abbr': 1, 'code': 1, 'title': 'Virtual temperature', 'units': 'K'},
            {'abbr': 2, 'code': 2, 'title': 'Potential temperature', 'units': 'K'},
            {'abbr': 3,
             'code': 3,
             'title': 'Pseudo-adiabatic potential temperature or equivalent potential '
                      'temperature',
             'units': 'K'},
            {'abbr': 4, 'code': 4, 'title': 'Maximum temperature', 'units': 'K'},
            {'abbr': 5, 'code': 5, 'title': 'Minimum temperature', 'units': 'K'},
            {'abbr': 6, 'code': 6, 'title': 'Dewpoint temperature', 'units': 'K'},
            {'abbr': 7,
             'code': 7,
             'title': 'Dewpoint depression (or deficit)',
             'units': 'K'},
            {'abbr': 8, 'code': 8, 'title': 'Lapse rate', 'units': 'K/m'},
            {'abbr': 9, 'code': 9, 'title': 'Temperature anomaly', 'units': 'K'},
            {'abbr': 10, 'code': 10, 'title': 'Latent heat net flux', 'units': 'W m-2'},
            {'abbr': 11, 'code': 11, 'title': 'Sensible heat net flux', 'units': 'W m-2'},
            {'abbr': 12, 'code': 12, 'title': 'Heat index', 'units': 'K'},
            {'abbr': 13, 'code': 13, 'title': 'Wind chill factor', 'units': 'K'},
            {'abbr': 14, 'code': 14, 'title': 'Minimum dewpoint depression', 'units': 'K'},
            {'abbr': 15,
             'code': 15,
             'title': 'Virtual potential temperature',
             'units': 'K'},
            {'abbr': 16,
             'code': 16,
             'title': 'Snow phase change heat flux',
             'units': 'W m-2'},
            {'abbr': 17, 'code': 17, 'title': 'Skin temperature', 'units': 'K'},
            {'abbr': 18,
             'code': 18,
             'title': 'Snow temperature (top of snow)',
             'units': 'K'},
            {'abbr': 19,
             'code': 19,
             'title': 'Turbulent transfer coefficient for heat',
             'units': 'Numeric'},
            {'abbr': 20,
             'code': 20,
             'title': 'Turbulent diffusion coefficient for heat',
             'units': 'm2/s'},
            {'abbr': 21, 'code': 21, 'title': 'Apparent temperature', 'units': 'K'},
            {'abbr': 22,
             'code': 22,
             'title': 'Temperature tendency due to short-wave radiation',
             'units': 'K s-1'},
            {'abbr': 23,
             'code': 23,
             'title': 'Temperature tendency due to long-wave radiation',
             'units': 'K s-1'},
            {'abbr': 24,
             'code': 24,
             'title': 'Temperature tendency due to short-wave radiation, clear sky',
             'units': 'K s-1'},
            {'abbr': 25,
             'code': 25,
             'title': 'Temperature tendency due to long-wave radiation, clear sky',
             'units': 'K s-1'},
            {'abbr': 26,
             'code': 26,
             'title': 'Temperature tendency due to parameterizations',
             'units': 'K s-1'},
            {'abbr': 27, 'code': 27, 'title': 'Wet bulb temperature', 'units': 'K'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
