def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Parcel lifted index (to 500 hPa)',
             'units': 'K'},
            {'abbr': 1,
             'code': 1,
             'title': 'Best lifted index (to 500 hPa)',
             'units': 'K'},
            {'abbr': 2, 'code': 2, 'title': 'K index', 'units': 'K'},
            {'abbr': 3, 'code': 3, 'title': 'KO index', 'units': 'K'},
            {'abbr': 4, 'code': 4, 'title': 'Total totals index', 'units': 'K'},
            {'abbr': 5, 'code': 5, 'title': 'Sweat index', 'units': 'Numeric'},
            {'abbr': 6,
             'code': 6,
             'title': 'Convective available potential energy',
             'units': 'J/kg'},
            {'abbr': 7, 'code': 7, 'title': 'Convective inhibition', 'units': 'J/kg'},
            {'abbr': 8, 'code': 8, 'title': 'Storm relative helicity', 'units': 'J/kg'},
            {'abbr': 9, 'code': 9, 'title': 'Energy helicity index', 'units': 'Numeric'},
            {'abbr': 10, 'code': 10, 'title': 'Surface lifted index', 'units': 'K'},
            {'abbr': 11, 'code': 11, 'title': 'Best (4-layer) lifted index', 'units': 'K'},
            {'abbr': 12, 'code': 12, 'title': 'Richardson number', 'units': 'Numeric'},
            {'abbr': 13, 'code': 13, 'title': 'Showalter index', 'units': 'K'},
            {'abbr': 14, 'code': 14, 'title': 'Reserved'},
            {'abbr': 15, 'code': 15, 'title': 'Updraft helicity', 'units': 'm2 s-2'},
            {'abbr': 16,
             'code': 16,
             'title': 'Bulk Richardson number',
             'units': 'Numeric'},
            {'abbr': 17,
             'code': 17,
             'title': 'Gradient Richardson number',
             'units': 'Numeric'},
            {'abbr': 18,
             'code': 18,
             'title': 'Flux Richardson number',
             'units': 'Numeric'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
