def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Fire outlook', 'units': 'Code table 4.224'},
            {'abbr': 1,
             'code': 1,
             'title': 'Fire outlook due to dry thunderstorm',
             'units': 'Code table 4.224'},
            {'abbr': 2, 'code': 2, 'title': 'Haines index', 'units': 'Numeric'},
            {'abbr': 3, 'code': 3, 'title': 'Fire burned area', 'units': '%'},
            {'abbr': 4, 'code': 4, 'title': 'Fosberg index', 'units': 'Numeric'},
            {'abbr': 5,
             'code': 5,
             'title': 'Fire weather index (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': 6,
             'code': 6,
             'title': 'Fine fuel moisture code (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': 7,
             'code': 7,
             'title': 'Duff moisture code (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': 8,
             'code': 8,
             'title': 'Drought code (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': 9,
             'code': 9,
             'title': 'Initial fire spread index (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': 10,
             'code': 10,
             'title': 'Fire build up index (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': 11,
             'code': 11,
             'title': 'Fire daily severity rating (Canadian forest service)',
             'units': 'Numeric'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
