def load(h):
    return ({'abbr': 'm', 'code': 0, 'title': 'Minute'},
            {'abbr': 'h', 'code': 1, 'title': 'Hour'},
            {'abbr': 'D', 'code': 2, 'title': 'Day'},
            {'abbr': 'M', 'code': 3, 'title': 'Month'},
            {'abbr': 'Y', 'code': 4, 'title': 'Year'},
            {'abbr': '10Y', 'code': 5, 'title': 'Decade', 'units': '10 years'},
            {'abbr': '30Y', 'code': 6, 'title': 'Normal', 'units': '30 years'},
            {'abbr': 'C', 'code': 7, 'title': 'Century', 'units': '100 years'},
            {'abbr': '3h', 'code': 10, 'title': '3 hours'},
            {'abbr': '6h', 'code': 11, 'title': '6 hours'},
            {'abbr': '12h', 'code': 12, 'title': '12 hours'},
            {'abbr': 's', 'code': 13, 'title': 'Second'},
            {'abbr': '15m', 'code': 14, 'title': '15 minutes'},
            {'abbr': '30m', 'code': 15, 'title': '30 minutes'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
