def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Clear sky probability', 'units': '%'},
            {'abbr': 1, 'code': 1, 'title': 'Cloud top temperature', 'units': 'K'},
            {'abbr': 2, 'code': 2, 'title': 'Cloud top pressure', 'units': 'Pa'},
            {'abbr': 3, 'code': 3, 'title': 'Cloud type', 'units': 'Code table 4.218'},
            {'abbr': 4, 'code': 4, 'title': 'Cloud phase', 'units': 'Code table 4.218'},
            {'abbr': 5, 'code': 5, 'title': 'Cloud optical depth', 'units': 'Numeric'},
            {'abbr': 6,
             'code': 6,
             'title': 'Cloud particle effective radius',
             'units': 'm'},
            {'abbr': 7, 'code': 7, 'title': 'Cloud liquid water path', 'units': 'kg m-2'},
            {'abbr': 8, 'code': 8, 'title': 'Cloud ice water path', 'units': 'kg m-2'},
            {'abbr': 9, 'code': 9, 'title': 'Cloud albedo', 'units': 'Numeric'},
            {'abbr': 10, 'code': 10, 'title': 'Cloud emissivity', 'units': 'Numeric'},
            {'abbr': 11,
             'code': 11,
             'title': 'Effective absorption optical depth ratio',
             'units': 'Numeric'},
            {'abbr': 30, 'code': 30, 'title': 'Measurement cost', 'units': 'Numeric'},
            {'abbr': 31,
             'code': 31,
             'title': 'Upper layer cloud optical depth',
             'units': 'Numeric'},
            {'abbr': 32,
             'code': 32,
             'title': 'Upper layer cloud top pressure',
             'units': 'Pa'},
            {'abbr': 33,
             'code': 33,
             'title': 'Upper layer cloud effective radius',
             'units': 'm'},
            {'abbr': 34,
             'code': 34,
             'title': 'Error in upper layer cloud optical depth',
             'units': 'Numeric'},
            {'abbr': 35,
             'code': 35,
             'title': 'Error in upper layer cloud top pressure',
             'units': 'Pa'},
            {'abbr': 36,
             'code': 36,
             'title': 'Error in upper layer cloud effective radius',
             'units': 'm'},
            {'abbr': 37,
             'code': 37,
             'title': 'Lower layer cloud optical depth',
             'units': 'Numeric'},
            {'abbr': 38,
             'code': 38,
             'title': 'Lower layer cloud top pressure',
             'units': 'Pa'},
            {'abbr': 39,
             'code': 39,
             'title': 'Error in lower layer cloud optical depth',
             'units': 'Numeric'},
            {'abbr': 40,
             'code': 40,
             'title': 'Error in lower layer cloud top pressure',
             'units': 'Pa'})
