def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Main thermocline depth', 'units': 'm'},
            {'abbr': 1, 'code': 1, 'title': 'Main thermocline anomaly', 'units': 'm'},
            {'abbr': 2, 'code': 2, 'title': 'Transient thermocline depth', 'units': 'm'},
            {'abbr': 3, 'code': 3, 'title': 'Salinity', 'units': 'kg/kg'},
            {'abbr': 4,
             'code': 4,
             'title': 'Ocean vertical heat diffusivity',
             'units': 'm2/s'},
            {'abbr': 5,
             'code': 5,
             'title': 'Ocean vertical salt diffusivity',
             'units': 'm2/s'},
            {'abbr': 6,
             'code': 6,
             'title': 'Ocean vertical momentum diffusivity',
             'units': 'm2/s'},
            {'abbr': 7, 'code': 7, 'title': 'Bathymetry', 'units': 'm'},
            {'abbr': 11,
             'code': 11,
             'title': 'Shape factor with respect to salinity profile',
             'units': '-'},
            {'abbr': 12,
             'code': 12,
             'title': 'Shape factor with respect to temperature profile in thermocline',
             'units': '-'},
            {'abbr': 13,
             'code': 13,
             'title': 'Attenuation coefficient of water with respect to solar radiation',
             'units': '/m'},
            {'abbr': 14, 'code': 14, 'title': 'Water depth', 'units': 'm'},
            {'abbr': 15, 'code': 15, 'title': 'Water temperature', 'units': 'K'},
            {'abbr': 16, 'code': 16, 'title': 'Water density (rho)', 'units': 'kg m-3'},
            {'abbr': 17,
             'code': 17,
             'title': 'Water density anomaly (sigma)',
             'units': 'kg m-3'},
            {'abbr': 18,
             'code': 18,
             'title': 'Water potential temperature (theta)',
             'units': 'K'},
            {'abbr': 19,
             'code': 19,
             'title': 'Water potential density (rho theta)',
             'units': 'kg m-3'},
            {'abbr': 20,
             'code': 20,
             'title': 'Water potential density anomaly (sigma theta)',
             'units': 'kg m-3'},
            {'abbr': 21, 'code': 21, 'title': 'Practical salinity', 'units': 'Numeric'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
