def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Volcanic ash probability', 'units': '%'},
            {'abbr': 1,
             'code': 1,
             'title': 'Volcanic ash cloud top temperature',
             'units': 'K'},
            {'abbr': 2,
             'code': 2,
             'title': 'Volcanic ash cloud top pressure',
             'units': 'Pa'},
            {'abbr': 3, 'code': 3, 'title': 'Volcanic ash cloud top height', 'units': 'm'},
            {'abbr': 4,
             'code': 4,
             'title': 'Volcanic ash cloud emissivity',
             'units': 'Numeric'},
            {'abbr': 5,
             'code': 5,
             'title': 'Volcanic ash effective absorption optical depth ratio',
             'units': 'Numeric'},
            {'abbr': 6,
             'code': 6,
             'title': 'Volcanic ash cloud optical depth',
             'units': 'Numeric'},
            {'abbr': 7,
             'code': 7,
             'title': 'Volcanic ash column density',
             'units': 'kg m-2'},
            {'abbr': 8,
             'code': 8,
             'title': 'Volcanic ash particle effective radius',
             'units': 'm'})
