def load(h):
    return ({'abbr': 0,
             'code': 0,
             'title': 'Lightning strike density',
             'units': 'm-2 s-1'},
            {'abbr': 1,
             'code': 1,
             'title': 'Lightning potential index (LPI)',
             'units': 'J kg-1'},
            {'abbr': 2,
             'code': 2,
             'title': 'Cloud-to-ground Lightning flash density',
             'units': 'km-2 day-1'},
            {'abbr': 3,
             'code': 3,
             'title': 'Cloud-to-cloud Lightning flash density',
             'units': 'km-2 day-1'},
            {'abbr': 4,
             'code': 4,
             'title': 'Total Lightning flash density',
             'units': 'km-2 day-1'})
