def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Probability of event below lower limit'},
            {'abbr': 1, 'code': 1, 'title': 'Probability of event above upper limit'},
            {'abbr': 2,
             'code': 2,
             'title': 'Probability of event between lower and upper limits',
             'units': 'the range includes the lower limit but not the upper limit'},
            {'abbr': 3, 'code': 3, 'title': 'Probability of event above lower limit'},
            {'abbr': 4, 'code': 4, 'title': 'Probability of event below upper limit'},
            {'abbr': 5, 'code': 5, 'title': 'Probability of event equal to lower limit'},
            {'abbr': 6,
             'code': 6,
             'title': 'Probability of event in above normal category'},
            {'abbr': 7,
             'code': 7,
             'title': 'Probability of event in near normal category'},
            {'abbr': 8,
             'code': 8,
             'title': 'Probability of event in below normal category'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
