def load(h):
    return ({'abbr': 'unknown', 'code': 0, 'title': 'Unknown'},
            {'abbr': 'no-ar-ce',
             'code': 1,
             'title': 'HARMONIE-AROME reanalysis by MetNorway on CARRA-East domain',
             'units': 'CARRA project'},
            {'abbr': 'no-ar-cw',
             'code': 2,
             'title': 'HARMONIE-AROME reanalysis by MetNorway on CARRA-West domain',
             'units': 'CARRA project'},
            {'abbr': 'no-ar-pa',
             'code': 3,
             'title': 'HARMONIE-AROME reanalysis by MetNorway on Pan-Arctic domain',
             'units': 'CARRA project'},
            {'abbr': 'se-al-ec',
             'code': 4,
             'title': 'HARMONIE-ALADIN reanalysis by SMHI on EURO-CORDEX domain',
             'units': 'CERRA project'},
            {'abbr': 'fr-ms-ec',
             'code': 5,
             'title': 'MESCAN-SURFEX surface reanalysis by Meteo-France on EURO-CORDEX '
                      'domain',
             'units': 'CERRA project'})
