def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Empty local section'},
            {'abbr': 1, 'code': 1, 'title': 'MARS labelling'},
            {'abbr': 5, 'code': 5, 'title': 'Forecast probability data'},
            {'abbr': 7, 'code': 7, 'title': 'Sensitivity data'},
            {'abbr': 9, 'code': 9, 'title': 'Singular vectors and ensemble perturbations'},
            {'abbr': 11, 'code': 11, 'title': 'Supplementary data used by the analysis'},
            {'abbr': 12,
             'code': 12,
             'title': 'Seasonal forecast monthly mean data for lagged systems'},
            {'abbr': 14, 'code': 14, 'title': 'Brightness temperature'},
            {'abbr': 15, 'code': 15, 'title': 'Seasonal forecast data'},
            {'abbr': 16, 'code': 16, 'title': 'Seasonal forecast monthly mean data'},
            {'abbr': 18, 'code': 18, 'title': 'Multianalysis ensemble data'},
            {'abbr': 20, 'code': 20, 'title': '4D variational increments'},
            {'abbr': 21, 'code': 21, 'title': 'Sensitive area predictions'},
            {'abbr': 24, 'code': 24, 'title': 'Satellite Channel Data'},
            {'abbr': 25, 'code': 25, 'title': '4DVar model errors'},
            {'abbr': 26,
             'code': 26,
             'title': 'MARS labelling or ensemble forecast data',
             'units': 'with hindcast support'},
            {'abbr': 28, 'code': 28, 'title': 'COSMO local area EPS'},
            {'abbr': 30,
             'code': 30,
             'title': 'Forecasting Systems with Variable Resolution'},
            {'abbr': 36,
             'code': 36,
             'title': 'MARS labelling for long window 4DVar system'},
            {'abbr': 38,
             'code': 38,
             'title': '4D variational increments for long window 4DVar system'},
            {'abbr': 39,
             'code': 39,
             'title': '4DVar model errors for long window 4Dvar system'},
            {'abbr': 41, 'code': 41, 'title': 'The European Flood Awareness System'},
            {'abbr': 42,
             'code': 42,
             'title': 'Lead Centre for Wave Forecast Verification'},
            {'abbr': 192, 'code': 192, 'title': 'Multiple ECMWF local definitions'},
            {'abbr': 300, 'code': 300, 'title': 'Multi-dimensional parameters'})
