def load(h):
    return ({'abbr': 'unknown', 'code': 0, 'title': 'Unknown'},
            {'abbr': 'ecmf', 'code': 1, 'title': 'Wave model run by ECMWF'},
            {'abbr': 'egrr', 'code': 2, 'title': 'Wave model run by UKMO'},
            {'abbr': 'fnmo', 'code': 3, 'title': 'Wave model run by FNMOC'},
            {'abbr': 'cwao', 'code': 4, 'title': 'Wave model run by ECCC'},
            {'abbr': 'kwbc', 'code': 5, 'title': 'Wave model run by NCEP'},
            {'abbr': 'lfpw', 'code': 6, 'title': 'Wave model run by METFR'},
            {'abbr': 'edzw', 'code': 7, 'title': 'Wave model run by DWD'},
            {'abbr': 'ammc', 'code': 8, 'title': 'Wave model run by BoM'},
            {'abbr': 'lops', 'code': 9, 'title': 'Wave model run by LOPS'},
            {'abbr': 'rjtd', 'code': 10, 'title': 'Wave model run by JMA'},
            {'abbr': 'rksl', 'code': 11, 'title': 'Wave model run by KMA'},
            {'abbr': 'lemm', 'code': 12, 'title': 'Wave model run by PRTOS'},
            {'abbr': 'ekmi', 'code': 13, 'title': 'Wave model run by DMI'},
            {'abbr': 'niwa', 'code': 14, 'title': 'Wave model run by NIWA'},
            {'abbr': 'enmi', 'code': 15, 'title': 'Wave model run by METNO'},
            {'abbr': 'sabm', 'code': 16, 'title': 'Wave model run by SHN/SM'},
            {'abbr': 'nzkl', 'code': 17, 'title': 'Wave model run by NZMS'},
            {'abbr': 'cnmc', 'code': 18, 'title': 'Wave model run by METEOAM'})
