def load(h):
    return ({'abbr': 'unknown', 'code': 0, 'title': 'unknown'},
            {'abbr': 'mogreps-mo-eua',
             'code': 1,
             'title': 'Unified model based LAM-EPS run by UK Met Office'},
            {'abbr': 'sreps-aemet-eua',
             'code': 2,
             'title': 'Multi model based LAM-EPS run by AEMET',
             'units': 'Spain'},
            {'abbr': 'srnwppeps-dwd-eua',
             'code': 3,
             'title': "Poor man's LAM-EPS run by DWD",
             'units': 'Germany'},
            {'abbr': 'cosmoleps-arpasimc-eu',
             'code': 4,
             'title': 'COSMO model based LAM-EPS run by ARPA-SIM',
             'units': 'Italy'},
            {'abbr': 'aladinlaef-zamg-eu',
             'code': 6,
             'title': 'ALADIN model based LAM-EPS run by ZAMG',
             'units': 'Austria'},
            {'abbr': 'cosmodeeps-dwd-eu',
             'code': 7,
             'title': 'COSMO model based LAM-EPS run by DWD',
             'units': 'Germany'},
            {'abbr': 'glameps-hirlamcons-eu',
             'code': 9,
             'title': 'ALADIN and HIRLAM models based LAM-EPS run by HIRLAM and ALADIN '
                      'consortium'},
            {'abbr': 'aromeeps-mf-eu',
             'code': 10,
             'title': 'AROME model based LAM-EPS run by Meteo-France'},
            {'abbr': 'hirlam-dmi-eu',
             'code': 11,
             'title': 'HIRLAM model based LAM-EPS run by DMI',
             'units': 'Denmark'},
            {'abbr': 'aladinhuneps-omsz-eu',
             'code': 12,
             'title': 'ALADIN model based LAM-EPS run by OMSZ',
             'units': 'Hungary'},
            {'abbr': 'pearp-mf-eu',
             'code': 13,
             'title': 'ARPEGE model based LAM-EPS run by Meteo-France'})
