def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'solution of 2-d Helmholtz equations - needed for restart(Numeric)'},
            {'abbr': 193,
             'code': 193,
             'title': 'Area weights for regular lon-lat grid(Numeric)'},
            {'abbr': 194,
             'code': 194,
             'title': 'Gauss Boaga Coordinates West to East,East Sector(m)'},
            {'abbr': 195,
             'code': 195,
             'title': 'Gauss Boaga Coordinates South to North,East Sector(m)'},
            {'abbr': 196,
             'code': 196,
             'title': 'Gauss Boaga Coordinates West to East, West Sector(m)'},
            {'abbr': 197,
             'code': 197,
             'title': 'Gauss Boaga Coordinates South to North, West Sector(m)'},
            {'abbr': 198,
             'code': 198,
             'title': 'Swiss coodinate',
             'units': 'south-north)(m'},
            {'abbr': 199,
             'code': 199,
             'title': 'Swiss coodinate',
             'units': 'west-east)(m'})
