def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'cloud base above msl, shallow convection(m)'},
            {'abbr': 193,
             'code': 193,
             'title': 'Cloud top above msl, shallow convection(m)'},
            {'abbr': 194,
             'code': 194,
             'title': 'base index (vertical level) of main convective cloud',
             'units': 'i)(Numeric'},
            {'abbr': 195,
             'code': 195,
             'title': 'top index (vertical level) of main convective cloud',
             'units': 'i)(Numeric'},
            {'abbr': 196,
             'code': 196,
             'title': 'Height of top of dry convection above MSL(m)'},
            {'abbr': 197, 'code': 197, 'title': 'Height of thermals above MSL(m)'},
            {'abbr': 198, 'code': 198, 'title': 'modified cloud depth for media(Numeric)'},
            {'abbr': 199, 'code': 199, 'title': 'modified cloud cover for media(Numeric)'},
            {'abbr': 201,
             'code': 201,
             'title': 'Konvektionsart',
             'units': '0..4)(Numeric'},
            {'abbr': 202, 'code': 202, 'title': 'dry convection top index(Numeric)'},
            {'abbr': 203, 'code': 203, 'title': 'Mass density of cloud droplets(kg m-3)'},
            {'abbr': 204, 'code': 204, 'title': 'Mass density of cloud ice(kg m-3)'},
            {'abbr': 205,
             'code': 205,
             'title': 'Possible astronomical maximum of sunshine(s)'},
            {'abbr': 206,
             'code': 206,
             'title': 'Relative duration of sunshine',
             'units': 'DURSUN * 100 / DURSON M)(%'})
