def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'Number of pollen in the reservoir',
             'units': 'previous timestep)(m-2'},
            {'abbr': 193,
             'code': 193,
             'title': 'Sum of released pollen into the reservoir',
             'units': 'daily sum)(m-2'},
            {'abbr': 194,
             'code': 194,
             'title': 'State of the season',
             'units': 'eq.zero before and after season, the higher, the more plants are '
                      'flowering)(0-1'},
            {'abbr': 195,
             'code': 195,
             'title': 'Height correction for emission (decreasing emission with height)',
             'units': '0-1'},
            {'abbr': 196,
             'code': 196,
             'title': 'Cumulated weighted 2m temperature sum of daily values for '
                      'pollen(deg C)'},
            {'abbr': 197,
             'code': 197,
             'title': 'Cumulated 2m temperature sum threshold for the start of pollen '
                      'season',
             'units': 'climatological)(deg C'},
            {'abbr': 198,
             'code': 198,
             'title': 'Cumulated 2m temperature sum threshold for the end of pollen '
                      'season',
             'units': 'climatological)(deg C'},
            {'abbr': 199,
             'code': 199,
             'title': 'Number of days since the start of pollen season',
             'units': 'if present day is in the season: zero outside season)(d'},
            {'abbr': 200,
             'code': 200,
             'title': 'Number of days since the start of pollen season',
             'units': 'if present day is outside the season: length of current season)(d'},
            {'abbr': 201, 'code': 201, 'title': 'Length of pollen season(d)'},
            {'abbr': 202,
             'code': 202,
             'title': 'Pollen number emission flux for',
             'units': 'm-2s-1'})
