def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'Tendency of turbulent kinetic energy(m2 s-3)'},
            {'abbr': 193, 'code': 193, 'title': 'Coriolis parameter(s-1)'},
            {'abbr': 194,
             'code': 194,
             'title': 'Kombination Niederschlag-Bewoelkung-Blauthermik',
             'units': 'cl_typ.tab)(Numeric'},
            {'abbr': 195,
             'code': 195,
             'title': 'Icing Base',
             'units': 'hft) - Icing Degree Composit(hft'},
            {'abbr': 196,
             'code': 196,
             'title': 'Icing Max Base',
             'units': 'hft) - Icing Degree Composit(hft'},
            {'abbr': 197,
             'code': 197,
             'title': 'Icing Max Top',
             'units': 'hft) - Icing Degree Composit(hft'},
            {'abbr': 198,
             'code': 198,
             'title': 'Icing Top',
             'units': 'hft) - Icing Degree Composit(hft'},
            {'abbr': 199,
             'code': 199,
             'title': 'Icing Vertical Code',
             'units': '1=continuous,2=discontinuous) - Icing Degree Composit(Numeric'},
            {'abbr': 200,
             'code': 200,
             'title': 'Icing Max Code',
             'units': '1=light,2=moderate,3=severe) - Icing Degree Composit(Numeric'},
            {'abbr': 201,
             'code': 201,
             'title': 'Icing Base',
             'units': 'hft) - Icing Scenario Composit(hft'},
            {'abbr': 202,
             'code': 202,
             'title': 'Icing Signifikant Base',
             'units': 'hft) - Icing Scenario Composit(hft'},
            {'abbr': 203,
             'code': 203,
             'title': 'Icing Signifikant Top',
             'units': 'hft) - Icing Scenario Composit(hft'},
            {'abbr': 204,
             'code': 204,
             'title': 'Icing Top',
             'units': 'hft) - Icing Scenario Composit(hft'},
            {'abbr': 205,
             'code': 205,
             'title': 'Icing Vertical Code',
             'units': '1=continuous,2=discontinuous) - Icing Scenario Composit(Numeric'},
            {'abbr': 206,
             'code': 206,
             'title': 'Icing Signifikant Code',
             'units': '1=general,2=convective,3=stratiform,4=freezing) - Icing Scenario '
                      'Composit(Numeric'},
            {'abbr': 207,
             'code': 207,
             'title': 'Icing Degree Code',
             'units': '1=light,2=moderate,3=severe)(Numeric'},
            {'abbr': 208,
             'code': 208,
             'title': 'Icing Scenario Code',
             'units': '1=general,2=convective,3=stratiform,4=freezing)(Numeric'},
            {'abbr': 209,
             'code': 209,
             'title': 'current weather',
             'units': 'symbol number: 0..9)(Numeric'},
            {'abbr': 216, 'code': 216, 'title': 'Eddy Dissipation Rate(m2/3 s-1)'},
            {'abbr': 217, 'code': 217, 'title': 'Ellrod Index(10-7 s-2)'},
            {'abbr': 218, 'code': 218, 'title': 'production of TKE(m2 s-3)'},
            {'abbr': 219,
             'code': 219,
             'title': 'buoyancy-production of TKE due to sub grid scale convection(m2 '
                      's-3)'},
            {'abbr': 220,
             'code': 220,
             'title': 'wake-production of TKE due to sub grid scale orography(m2 s-3)'},
            {'abbr': 221,
             'code': 221,
             'title': 'shear-production of TKE due to separated horizontal shear modes(m2 '
                      's-3)'},
            {'abbr': 222,
             'code': 222,
             'title': 'Albedo - diffusive solar',
             'units': '0.3 - 0.7 m-6)(%'},
            {'abbr': 223,
             'code': 223,
             'title': 'Albedo - near infrared - time average',
             'units': '0.7 - 5.0 m-6)(%'},
            {'abbr': 224,
             'code': 224,
             'title': 'Eddy Dissipation Rate Total Col-Max. Upper FIR',
             'units': '< FL245)(m2/3 s-1'},
            {'abbr': 225,
             'code': 225,
             'title': 'Eddy Dissipation Rate Total Col-Max. Lower UIR',
             'units': '<FL335)(m2/3 s-1'},
            {'abbr': 226,
             'code': 226,
             'title': 'Eddy Dissipation Rate Total Col-Max. Upper UIR',
             'units': '<FL450)(m2/3 s-1'},
            {'abbr': 227, 'code': 227, 'title': 'Eddy dissipitation rate of TKE(m2 s-3)'},
            {'abbr': 228,
             'code': 228,
             'title': 'Eddy Dissipation Rate Total Col-Max. Lower FIR',
             'units': '< FL165)(m2/3 s-1'},
            {'abbr': 229,
             'code': 229,
             'title': 'probability density function of EDP for turbulence greater well '
                      'defined threshold and model grid box(%)'},
            {'abbr': 230, 'code': 230, 'title': 'Ellrod and Knapp turbulence index1(s-2)'},
            {'abbr': 231, 'code': 231, 'title': 'Ellrod and Knapp turbulence index2(s-2)'},
            {'abbr': 232,
             'code': 232,
             'title': 'Divergence trend',
             'units': 'scaled divergence tendency needed for CAT_DVI)(s-2'},
            {'abbr': 233,
             'code': 233,
             'title': 'Divergence modified turbulence index',
             'units': 'Ellrod and Knox)(s-2'},
            {'abbr': 234,
             'code': 234,
             'title': 'sea ice albedo - diffusive solar',
             'units': '0.3 - 5.0 m-6)(%'},
            {'abbr': 235,
             'code': 235,
             'title': 'Random pattern for the stochastically perturbed parametrization '
                      'tendencies(Numeric)'})
