def load(h):
    return ({'abbr': 1,
             'code': 1,
             'title': 'Probability of 1h total precipitation >= 10mm(kg m2)'},
            {'abbr': 3,
             'code': 3,
             'title': 'Probability of 1h total precipitation >= 25mm(kg m2)'},
            {'abbr': 14,
             'code': 14,
             'title': 'Probability of 6h total precipitation >= 20mm(kg m2)'},
            {'abbr': 17,
             'code': 17,
             'title': 'Probability of 6h total precipitation >= 35mm(kg m2)'},
            {'abbr': 26,
             'code': 26,
             'title': 'Probability of 12h total precipitation >= 25mm(kg m2)'},
            {'abbr': 29,
             'code': 29,
             'title': 'Probability of 12h total precipitation >= 40mm(kg m2)'},
            {'abbr': 32,
             'code': 32,
             'title': 'Probability of 12h total precipitation >= 70mm(kg m2)'},
            {'abbr': 69,
             'code': 69,
             'title': 'Probability of 6h accumulated snow >=0.5cm(kg m2)'},
            {'abbr': 70,
             'code': 70,
             'title': 'Probability of 6h accumulated snow >= 5cm(kg m2)'},
            {'abbr': 71,
             'code': 71,
             'title': 'Probability of 6h accumulated snow >= 10cm(kg m2)'},
            {'abbr': 72,
             'code': 72,
             'title': 'Probability of 12h accumulated snow >=0.5cm(kg m2)'},
            {'abbr': 74,
             'code': 74,
             'title': 'Probability of 12h accumulated snow >= 10cm(kg m2)'},
            {'abbr': 75,
             'code': 75,
             'title': 'Probability of 12h accumulated snow >= 15cm(kg m2)'},
            {'abbr': 77,
             'code': 77,
             'title': 'Probability of 12h accumulated snow >= 25cm(kg m2)'},
            {'abbr': 132,
             'code': 132,
             'title': 'Probability of 1h maximum wind gust speed >= 14m/s(m s-1)'},
            {'abbr': 134,
             'code': 134,
             'title': 'Probability of 1h maximum wind gust speed >= 18m/s(m s-1)'},
            {'abbr': 136,
             'code': 136,
             'title': 'Probability of 1h maximum wind gust speed >= 25m/s(m s-1)'},
            {'abbr': 137,
             'code': 137,
             'title': 'Probability of 1h maximum wind gust speed >= 29m/s(m s-1)'},
            {'abbr': 138,
             'code': 138,
             'title': 'Probability of 1h maximum wind gust speed >= 33m/s(m s-1)'},
            {'abbr': 139,
             'code': 139,
             'title': 'Probability of 1h maximum wind gust speed >= 39m/s(m s-1)'},
            {'abbr': 191,
             'code': 191,
             'title': 'Probability of black ice during 1h(Numeric)'},
            {'abbr': 197,
             'code': 197,
             'title': 'Probability of thunderstorm during 1h(Numeric)'},
            {'abbr': 198,
             'code': 198,
             'title': 'Probability of heavy thunderstorm during 1h(Numeric)'},
            {'abbr': 199,
             'code': 199,
             'title': 'Probability of severe thunderstorm during 1h(Numeric)'},
            {'abbr': 212,
             'code': 212,
             'title': 'Probability of snowdrift during 12h(Numeric)'},
            {'abbr': 213,
             'code': 213,
             'title': 'Probability of strong snowdrift during 12h(Numeric)'},
            {'abbr': 232,
             'code': 232,
             'title': 'Probability of temperature < 0 deg C during 1h(K)'},
            {'abbr': 236,
             'code': 236,
             'title': 'Probability of temperature <= -10 deg C during 6h(K)'})
