def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'zonal wind tendency due to convection(m s-2)'},
            {'abbr': 193,
             'code': 193,
             'title': 'meridional wind tendency due to convection(m s-2)'},
            {'abbr': 194,
             'code': 194,
             'title': 'zonal wind tendency due to subgrid scale oro.(m s-2)'},
            {'abbr': 195,
             'code': 195,
             'title': 'meridional wind tendency due to subgrid scale oro.(m s-2)'},
            {'abbr': 196, 'code': 196, 'title': 'Kinetic Energy(J kg-1)'},
            {'abbr': 197, 'code': 197, 'title': 'Absolute vorticity advection(s-2)'},
            {'abbr': 198, 'code': 198, 'title': 'relative vorticity,U-component(s-1)'},
            {'abbr': 199, 'code': 199, 'title': 'relative vorticity,V-component(s-1)'},
            {'abbr': 200, 'code': 200, 'title': 'Atmospheric resistance(s m-1)'},
            {'abbr': 201,
             'code': 201,
             'title': 'Mean vertical wind shear for specified layer or layer-mean '
                      'vertical wind shear(s-1)'},
            {'abbr': 202,
             'code': 202,
             'title': 'Norm of',
             'units': 'vertical) wind shear vector between two levels(m s-1'},
            {'abbr': 203, 'code': 203, 'title': 'Threshold friction velocity(m s-1)'},
            {'abbr': 205, 'code': 205, 'title': 'Maximum 10m convective gust(ms-1)'},
            {'abbr': 206,
             'code': 206,
             'title': 'Maximum rotation amplitude (positive or negative)',
             'units': 'over given time interval and column)(s-1'},
            {'abbr': 207,
             'code': 207,
             'title': 'Maximum updraft track',
             'units': 'over given time interval and column)(m s-1'})
