def load(h):
    return ({'abbr': 33,
             'code': 33,
             'title': 'mass concentration of dust',
             'units': 'minimum mode)(kg m-3'},
            {'abbr': 34,
             'code': 34,
             'title': 'mass concentration of dust',
             'units': 'medium mode)(kg m-3'},
            {'abbr': 35,
             'code': 35,
             'title': 'mass concentration of dust',
             'units': 'maximum mode)(kg m-3'},
            {'abbr': 72,
             'code': 72,
             'title': 'number concentration of dust',
             'units': 'minimum mode)(m-3'},
            {'abbr': 73,
             'code': 73,
             'title': 'number concentration of dust',
             'units': 'medium mode)(m-3'},
            {'abbr': 74,
             'code': 74,
             'title': 'number concentration of dust',
             'units': 'maximum mode)(m-3'},
            {'abbr': 251,
             'code': 251,
             'title': 'mass concentration of dust',
             'units': 'sum of all modes)(kg m-3'},
            {'abbr': 252,
             'code': 252,
             'title': 'number concentration of dust',
             'units': 'sum of all modes)(m-3'})
