def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'vertical integral of divergence of total water content',
             'units': 's)(kg m-2'},
            {'abbr': 193, 'code': 193, 'title': 'subgrid scale cloud water(kg kg-1)'},
            {'abbr': 194, 'code': 194, 'title': 'subgridscale cloud ice(kg kg-1)'},
            {'abbr': 195,
             'code': 195,
             'title': 'specific cloud water content, convective cloud(kg kg-1)'},
            {'abbr': 196,
             'code': 196,
             'title': 'Specific content of precipitation particles',
             'units': 'needed for water loading)(kg kg-1'},
            {'abbr': 197,
             'code': 197,
             'title': 'Specific humitiy tendency due to convection(kg kg-1 s-1)'},
            {'abbr': 198,
             'code': 198,
             'title': 'Tendency of specific cloud liquid water content due to '
                      'conversion(kg kg-1 s-1)'},
            {'abbr': 199,
             'code': 199,
             'title': 'tendency of specific cloud ice content due to convection(kg kg-1 '
                      's-1)'},
            {'abbr': 200,
             'code': 200,
             'title': 'Specific humitiy tendency due to grid scale precipitation(kg kg-1 '
                      's-1)'},
            {'abbr': 201,
             'code': 201,
             'title': 'tendency of specific cloud liquid water content due to grid scale '
                      'precipitation(kg kg-1 s-1)'},
            {'abbr': 202,
             'code': 202,
             'title': 'tendency of specific cloud ice content due to grid scale '
                      'precipitation(kg kg-1 s-1)'},
            {'abbr': 203,
             'code': 203,
             'title': 'Fresh snow factor',
             'units': 'weighting function for albedo indicating freshness of '
                      'snow)(Numeric'},
            {'abbr': 204, 'code': 204, 'title': 'Height of snow fall limit above MSL(m)'},
            {'abbr': 205,
             'code': 205,
             'title': 'Massflux at convective cloud base(kg m-2 s-1)'},
            {'abbr': 206,
             'code': 206,
             'title': 'moisture convergence for Kuo-type closure(s-1)'},
            {'abbr': 207, 'code': 207, 'title': 'tendency of specific humidity(s-1)'},
            {'abbr': 208, 'code': 208, 'title': 'water vapor flux(s-1 m-2)'},
            {'abbr': 209,
             'code': 209,
             'title': 'Niederschlagsdargebot aus Modell SNOW(kg m-2)'},
            {'abbr': 210,
             'code': 210,
             'title': 'Liquid water content in the snow in - multi level(kg m-2)'},
            {'abbr': 211,
             'code': 211,
             'title': 'Specific humidity',
             'units': 'diagnostic)(kg kg-1'},
            {'abbr': 212,
             'code': 212,
             'title': 'Specific cloud water content',
             'units': 'diagnostic)(kg kg-1'},
            {'abbr': 213,
             'code': 213,
             'title': 'Specific cloud ice content',
             'units': 'diagnostic)(kg kg-1'},
            {'abbr': 214,
             'code': 214,
             'title': 'Total column integrated water vapour',
             'units': 'diagnostic)(kg m-2'},
            {'abbr': 215,
             'code': 215,
             'title': 'Total column integrated cloud water',
             'units': 'diagnostic)(kg m-2'},
            {'abbr': 216,
             'code': 216,
             'title': 'Total column integrated cloud ice',
             'units': 'diagnostic)(kg m-2'},
            {'abbr': 217,
             'code': 217,
             'title': 'Specific number concentration of snow(kg-1)'},
            {'abbr': 218,
             'code': 218,
             'title': 'Specific number concentration of graupel(kg-1)'},
            {'abbr': 219,
             'code': 219,
             'title': 'Specific number concentration of hail(kg-1)'},
            {'abbr': 220, 'code': 220, 'title': 'relative humidity over mixed phase(%)'},
            {'abbr': 221, 'code': 221, 'title': 'Number density of snow(m-3)'},
            {'abbr': 222, 'code': 222, 'title': 'Number density of graupel(m-3)'},
            {'abbr': 223, 'code': 223, 'title': 'Number density of hail(m-3)'},
            {'abbr': 224, 'code': 224, 'title': 'Mass density of rain(kg m-3)'},
            {'abbr': 225, 'code': 225, 'title': 'Mass density of snow(kg m-3)'},
            {'abbr': 226, 'code': 226, 'title': 'Mass density of graupel(kg m-3)'},
            {'abbr': 227, 'code': 227, 'title': 'Mass density of hail(kg m-3)'},
            {'abbr': 228,
             'code': 228,
             'title': 'Specific number concentration of rain(kg-1)'},
            {'abbr': 229, 'code': 229, 'title': 'Number density of rain(m-3)'},
            {'abbr': 230, 'code': 230, 'title': 'rain-drain-from-snowpack(kg m-2)'},
            {'abbr': 231, 'code': 231, 'title': 'Cloud ice ratio qi/(qc+qi)(%)'},
            {'abbr': 232,
             'code': 232,
             'title': 'Percentage of convective precipitation',
             'units': 'from total prec)(%'},
            {'abbr': 233,
             'code': 233,
             'title': 'Percentage of precipitation in snow',
             'units': 'from total prec.)(%'},
            {'abbr': 234,
             'code': 234,
             'title': 'Standard deviation of saturation deficit(Numeric)'},
            {'abbr': 235,
             'code': 235,
             'title': 'Maximum snow height during contiguous accumulating snow period',
             'units': 'coupled with snow age)(m'})
