def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Wind direction in azimuth class(Numeric)'},
            {'abbr': 1,
             'code': 1,
             'title': 'Along-wind lagrangian timescale',
             'units': 'Hanna)(s'},
            {'abbr': 2,
             'code': 2,
             'title': 'Cross-wind lagrangian timescale',
             'units': 'Hanna)(s'},
            {'abbr': 3,
             'code': 3,
             'title': 'Vertical lagrangian timescale',
             'units': 'Hanna)(s'},
            {'abbr': 4,
             'code': 4,
             'title': 'Zonal lagrangian timescale (direct)',
             'units': 'Hanna)(s'},
            {'abbr': 5,
             'code': 5,
             'title': 'Meridional lagrangian timescale (direct)',
             'units': 'Hanna)(s'},
            {'abbr': 6,
             'code': 6,
             'title': 'Vertical lagrangian timescale (direct)',
             'units': 'Hanna)(s'},
            {'abbr': 7,
             'code': 7,
             'title': 'Along-wind velocity fluctuation',
             'units': 'Hanna)(m s-1'},
            {'abbr': 8,
             'code': 8,
             'title': 'Cross-wind velocity fluctuation',
             'units': 'Hanna)(m s-1'},
            {'abbr': 9,
             'code': 9,
             'title': 'Vertical velocity fluctuation',
             'units': 'Hanna)(m s-1'},
            {'abbr': 10,
             'code': 10,
             'title': 'Zonal velocity fluctuation',
             'units': 'Hanna)(m s-1'},
            {'abbr': 11,
             'code': 11,
             'title': 'Meridional velocity fluctuation',
             'units': 'Hanna)(m s-1'},
            {'abbr': 12,
             'code': 12,
             'title': 'Vertical velocity fluctuation',
             'units': 'Hanna)(m s-1'})
