def load(h):
    return ({'abbr': 193, 'code': 193, 'title': 'wind sea period', 'units': 's'},
            {'abbr': 194, 'code': 194, 'title': 'swell period', 'units': 's'},
            {'abbr': 195, 'code': 195, 'title': 'total wave peak period', 'units': 's'},
            {'abbr': 196, 'code': 196, 'title': 'total wave mean period', 'units': 's'},
            {'abbr': 197, 'code': 197, 'title': 'total Tm1 period', 'units': 's'},
            {'abbr': 198, 'code': 198, 'title': 'total Tm2 period', 'units': 's'},
            {'abbr': 199,
             'code': 199,
             'title': 'total directional spread',
             'units': 'degree true'},
            {'abbr': 200, 'code': 200, 'title': 'friction velocity', 'units': 'm s**-1'},
            {'abbr': 201,
             'code': 201,
             'title': 'Peak frequency',
             'units': 'interpolated)(Hz'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
