def load(h):
    return ({'abbr': 192,
             'code': 192,
             'title': 'sum of contributions to evaporation(kg m-2)'},
            {'abbr': 193,
             'code': 193,
             'title': 'total transpiration from all soil layers(kg m-2)'},
            {'abbr': 194, 'code': 194, 'title': 'total forcing at soil surface(W m-2)'},
            {'abbr': 195, 'code': 195, 'title': 'residuum of soil moisture(kg m-2)'},
            {'abbr': 196,
             'code': 196,
             'title': 'soil type of grid',
             'units': '1...9, local soilType.table)(Numeric'},
            {'abbr': 197,
             'code': 197,
             'title': 'variance of soil moisture content',
             'units': '10-100)(kg2 m-4'},
            {'abbr': 198,
             'code': 198,
             'title': 'covariance of soil moisture content',
             'units': 'kg2 m-4'},
            {'abbr': 199, 'code': 199, 'title': 'surface emissivity(Numeric)'},
            {'abbr': 200,
             'code': 200,
             'title': 'soil moisture index',
             'units': 'multilayers)(Numeric'})
