def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'geostrophische Vorticityadvektion(s-2)'},
            {'abbr': 1,
             'code': 1,
             'title': 'Geostrophic thickness advection(m3 kg-1 s-1)'},
            {'abbr': 2, 'code': 2, 'title': 'Schichtdickenadvektion(m3 kg-1 s-1)'},
            {'abbr': 3, 'code': 3, 'title': 'Winddivergenz(s-1)'},
            {'abbr': 4,
             'code': 4,
             'title': 'Q-Vektor senkrecht zu den Isothermen(m2 kg-1 s-1)'},
            {'abbr': 5,
             'code': 5,
             'title': 'Wind X-Komponente auf isentropen Flaechen(m s-1)'},
            {'abbr': 6,
             'code': 6,
             'title': 'Wind Y-Komponente auf isentropen Flaechen(m s-1)'},
            {'abbr': 7, 'code': 7, 'title': 'geostrophische Vorticity(s-1)'},
            {'abbr': 8,
             'code': 8,
             'title': 'Forcing rechte Seite Omegagleichung(m kg-1 s-1)'},
            {'abbr': 9,
             'code': 9,
             'title': 'Q-Vektor X-Komponente',
             'units': 'geostrophisch)(m2 kg-1 s-1'},
            {'abbr': 10,
             'code': 10,
             'title': 'Q-Vektor Y-Komponente',
             'units': 'geostrophisch)(m2 kg-1 s-1'},
            {'abbr': 11,
             'code': 11,
             'title': 'Divergenz Q',
             'units': 'geostrophisch)(m kg-1 s-1'},
            {'abbr': 12,
             'code': 12,
             'title': 'Q-Vektor senkrecht zu d. Isothermen',
             'units': 'geostrophisch)(m2 kg-1 s-1'},
            {'abbr': 13,
             'code': 13,
             'title': 'Q-Vektor parallel zu d. Isothermen',
             'units': 'geostrophisch)(m2 kg-1 s-1'},
            {'abbr': 14, 'code': 14, 'title': 'Divergenz Qn geostrophisch(m kg-1 s-1)'},
            {'abbr': 15, 'code': 15, 'title': 'Divergenz Qs geostrophisch(m kg-1 s-1)'},
            {'abbr': 16, 'code': 16, 'title': 'Frontogenesefunktion(K2 m-2 s-1)'},
            {'abbr': 17, 'code': 17, 'title': 'Divergenz(m kg-1 s-1)'},
            {'abbr': 18,
             'code': 18,
             'title': 'Q-Vektor parallel zu den Isothermen(m2 kg-1 s-1)'},
            {'abbr': 19, 'code': 19, 'title': 'Divergenz Qn(m kg-1 s-1)'},
            {'abbr': 20, 'code': 20, 'title': 'Divergenz Qs(m kg-1 s-1)'},
            {'abbr': 21, 'code': 21, 'title': 'Frontogenesis function(Km kg-1 s-1)'},
            {'abbr': 22, 'code': 22, 'title': 'Clear Air Turbulence Index(s-1)'},
            {'abbr': 23,
             'code': 23,
             'title': 'Potentielle Vorticity',
             'units': 'auf Druckflaechen, nicht isentrop)(K m2 kg-1 s-1'},
            {'abbr': 24,
             'code': 24,
             'title': 'Hoehe der Konvektionsuntergrenze ueber nn(m)'},
            {'abbr': 25,
             'code': 25,
             'title': 'Isentrope potentielle Vorticity(K m2 kg-1 s-1)'},
            {'abbr': 26, 'code': 26, 'title': 'Relative geostrophic vorticity(s-1)'},
            {'abbr': 27,
             'code': 27,
             'title': 'Relative geostrophic vorticity advection(s-2)'},
            {'abbr': 28, 'code': 28, 'title': 'Wind divergence', 'units': '3D)(s-1'},
            {'abbr': 29, 'code': 29, 'title': 'Deformation of horizontal wind field(s-1)'})
