def load(h):
    return ({'abbr': 192, 'code': 192, 'title': 'bias corrected ensemble forecast'},
            {'abbr': 193, 'code': 193, 'title': 'calibrated forecast'},
            {'abbr': 194, 'code': 194, 'title': 'calibrated ensemble f.'},
            {'abbr': 195, 'code': 195, 'title': 'interpolated analysis/forecast'},
            {'abbr': 196, 'code': 196, 'title': 'invariant data'},
            {'abbr': 197, 'code': 197, 'title': 'smoothed forecast'},
            {'abbr': 198, 'code': 198, 'title': 'smoothed and calibrated forecast'},
            {'abbr': 199,
             'code': 199,
             'title': 'probability forecast derived by neighbourhood method'},
            {'abbr': 201, 'code': 201, 'title': 'diff. analysis - first guess'},
            {'abbr': 200, 'code': 200, 'title': 'diff. init. analysis - analysis*'},
            {'abbr': 202, 'code': 202, 'title': 'nudging'},
            {'abbr': 203, 'code': 203, 'title': 'nudgecast'},
            {'abbr': 204, 'code': 204, 'title': 'product derived by statistical model'},
            {'abbr': 205,
             'code': 205,
             'title': 'deterministic forecast on ensemble mean(DOM)'},
            {'abbr': 220, 'code': 220, 'title': 'postprocessing'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
