def load(h):
    return ({'abbr': 25,
             'code': 25,
             'title': 'Highest level where radar reflectivity exceeds the specified value',
             'units': 'echo top for a given threshold of reflectivity'},
            {'abbr': 'ML',
             'code': 192,
             'title': 'ML start level of mixed layer parcel(CAPE/CIN)'},
            {'abbr': 'MU',
             'code': 193,
             'title': 'MU start level of most unstable parcel(CAPE/CIN)'},
            {'abbr': 'LFC', 'code': 194, 'title': 'Level of free convection'},
            {'abbr': 'radarElevComposite',
             'code': 199,
             'title': 'radarElevComposite radarElevComposite'},
            {'abbr': 'hor', 'code': 201, 'title': 'Surface: horizontal plane'},
            {'abbr': 'vE', 'code': 202, 'title': 'Surface: vertical plane facing east'},
            {'abbr': 'vN', 'code': 203, 'title': 'Surface: vertical plane facing north'},
            {'abbr': 'vS', 'code': 204, 'title': 'Surface: vertical plane facing south'},
            {'abbr': 'vW', 'code': 205, 'title': 'Surface: vertical plane facing west'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
