def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'main run'},
            {'abbr': 1, 'code': 1, 'title': 'pre-assimilation'},
            {'abbr': 2, 'code': 2, 'title': 'assimilation'},
            {'abbr': 3, 'code': 3, 'title': 'test'},
            {'abbr': 4, 'code': 4, 'title': 'onscreen analysis'},
            {'abbr': 5, 'code': 5, 'title': 'WarnMOS'},
            {'abbr': 100, 'code': 100, 'title': 'Blauthermik'},
            {'abbr': 'SSO',
             'code': 101,
             'title': 'SSO - wake - production of TKE due to sub grid scale orography'},
            {'abbr': 'HSH',
             'code': 102,
             'title': 'HSH - shear - production of TKE due to separated horizontal shear '
                      'modes'},
            {'abbr': 'CON',
             'code': 103,
             'title': 'CON - buoyancy - production of TKE due to sub grid scale '
                      'convection'},
            {'abbr': 'A', 'code': 128, 'title': 'Modell-Bezug'},
            {'abbr': 'B', 'code': 129, 'title': 'Modell-Bezug'},
            {'abbr': 'AB', 'code': 130, 'title': 'Modell-Bezug'},
            {'abbr': 'C', 'code': 131, 'title': 'Modell-Bezug'},
            {'abbr': 'AC', 'code': 132, 'title': 'Modell-Bezug'},
            {'abbr': 'BC', 'code': 133, 'title': 'Modell-Bezug'},
            {'abbr': 'ABC', 'code': 134, 'title': 'Modell-Bezug'},
            {'abbr': 'D', 'code': 135, 'title': 'Modell-Bezug'},
            {'abbr': 'AD', 'code': 136, 'title': 'Modell-Bezug'},
            {'abbr': 'BD', 'code': 137, 'title': 'Modell-Bezug'},
            {'abbr': 'ABD', 'code': 138, 'title': 'Modell-Bezug'},
            {'abbr': 'CD', 'code': 139, 'title': 'Modell-Bezug'},
            {'abbr': 'ACD', 'code': 140, 'title': 'Modell-Bezug'},
            {'abbr': 'BCD', 'code': 141, 'title': 'Modell-Bezug'},
            {'abbr': 'ABCD', 'code': 142, 'title': 'Modell-Bezug'},
            {'abbr': 'E', 'code': 143, 'title': 'Modell-Bezug'},
            {'abbr': 'AE', 'code': 144, 'title': 'Modell-Bezug'},
            {'abbr': 'BE', 'code': 145, 'title': 'Modell-Bezug'},
            {'abbr': 'ABE', 'code': 146, 'title': 'Modell-Bezug'},
            {'abbr': 'CE', 'code': 147, 'title': 'Modell-Bezug'},
            {'abbr': 'ACE', 'code': 148, 'title': 'Modell-Bezug'},
            {'abbr': 'BCE', 'code': 149, 'title': 'Modell-Bezug'},
            {'abbr': 'ABCE', 'code': 150, 'title': 'Modell-Bezug'},
            {'abbr': 'DE', 'code': 151, 'title': 'Modell-Bezug'},
            {'abbr': 'ADE', 'code': 152, 'title': 'Modell-Bezug'},
            {'abbr': 'BDE', 'code': 153, 'title': 'Modell-Bezug'},
            {'abbr': 'ABDE', 'code': 154, 'title': 'Modell-Bezug'},
            {'abbr': 'CDE', 'code': 155, 'title': 'Modell-Bezug'},
            {'abbr': 'ACDE', 'code': 156, 'title': 'Modell-Bezug'},
            {'abbr': 'BCDE', 'code': 157, 'title': 'Modell-Bezug'},
            {'abbr': 'ABCDE', 'code': 158, 'title': 'Modell-Bezug'},
            {'abbr': 'NIL', 'code': 255, 'title': 'missing'})
