def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Soil type', 'units': 'Code table 4.213'},
            {'abbr': 1, 'code': 1, 'title': 'Upper layer soil temperature', 'units': 'K'},
            {'abbr': 2,
             'code': 2,
             'title': 'Upper layer soil moisture',
             'units': 'kg m-3'},
            {'abbr': 3,
             'code': 3,
             'title': 'Lower layer soil moisture',
             'units': 'kg m-3'},
            {'abbr': 4, 'code': 4, 'title': 'Bottom layer soil temperature', 'units': 'K'},
            {'abbr': 5,
             'code': 5,
             'title': 'Liquid volumetric soil moisture (non-frozen)',
             'units': 'Proportion'},
            {'abbr': 6,
             'code': 6,
             'title': 'Number of soil layers in root zone',
             'units': 'Numeric'},
            {'abbr': 7,
             'code': 7,
             'title': 'Transpiration stress-onset (soil moisture)',
             'units': 'Proportion'},
            {'abbr': 8,
             'code': 8,
             'title': 'Direct evaporation cease (soil moisture)',
             'units': 'Proportion'},
            {'abbr': 9, 'code': 9, 'title': 'Soil porosity', 'units': 'Proportion'},
            {'abbr': 10,
             'code': 10,
             'title': 'Liquid volumetric soil moisture (non-frozen)',
             'units': 'm3 m-3'},
            {'abbr': 11,
             'code': 11,
             'title': 'Volumetric transpiration stress-onset (soil moisture)',
             'units': 'm3 m-3'},
            {'abbr': 12,
             'code': 12,
             'title': 'Transpiration stress-onset (soil moisture)',
             'units': 'kg m-3'},
            {'abbr': 13,
             'code': 13,
             'title': 'Volumetric direct evaporation cease (soil moisture)',
             'units': 'm3 m-3'},
            {'abbr': 14,
             'code': 14,
             'title': 'Direct evaporation cease (soil moisture)',
             'units': 'kg m-3'},
            {'abbr': 15, 'code': 15, 'title': 'Soil porosity', 'units': 'm3 m-3'},
            {'abbr': 16,
             'code': 16,
             'title': 'Volumetric saturation of soil moisture',
             'units': 'm3 m-3'},
            {'abbr': 17,
             'code': 17,
             'title': 'Saturation of soil moisture',
             'units': 'kg m-3'},
            {'abbr': 18, 'code': 18, 'title': 'Soil temperature', 'units': 'K'},
            {'abbr': 19, 'code': 19, 'title': 'Soil moisture', 'units': 'kg m-3'},
            {'abbr': 20,
             'code': 20,
             'title': 'Column-integrated soil moisture',
             'units': 'kg m-2'},
            {'abbr': 21, 'code': 21, 'title': 'Soil ice', 'units': 'kg m-3'},
            {'abbr': 22,
             'code': 22,
             'title': 'Column-integrated soil ice',
             'units': 'kg m-2'},
            {'abbr': 23,
             'code': 23,
             'title': 'Liquid water in snow pack',
             'units': 'kg m-2'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
