def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Scaled radiance', 'units': 'Numeric'},
            {'abbr': 1, 'code': 1, 'title': 'Scaled albedo', 'units': 'Numeric'},
            {'abbr': 2,
             'code': 2,
             'title': 'Scaled brightness temperature',
             'units': 'Numeric'},
            {'abbr': 3,
             'code': 3,
             'title': 'Scaled precipitable water',
             'units': 'Numeric'},
            {'abbr': 4, 'code': 4, 'title': 'Scaled lifted index', 'units': 'Numeric'},
            {'abbr': 5,
             'code': 5,
             'title': 'Scaled cloud top pressure',
             'units': 'Numeric'},
            {'abbr': 6, 'code': 6, 'title': 'Scaled skin temperature', 'units': 'Numeric'},
            {'abbr': 7, 'code': 7, 'title': 'Cloud mask', 'units': 'Code table 4.217'},
            {'abbr': 8,
             'code': 8,
             'title': 'Pixel scene type',
             'units': 'Code table 4.218'},
            {'abbr': 9,
             'code': 9,
             'title': 'Fire detection indicator',
             'units': 'Code table 4.223'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
