def load(h):
    return ({'abbr': 0, 'code': 0, 'title': 'Analysis'},
            {'abbr': 1, 'code': 1, 'title': 'Initialization'},
            {'abbr': 2, 'code': 2, 'title': 'Forecast'},
            {'abbr': 3, 'code': 3, 'title': 'Bias corrected forecast'},
            {'abbr': 4, 'code': 4, 'title': 'Ensemble forecast'},
            {'abbr': 5, 'code': 5, 'title': 'Probability forecast'},
            {'abbr': 6, 'code': 6, 'title': 'Forecast error'},
            {'abbr': 7, 'code': 7, 'title': 'Analysis error'},
            {'abbr': 8, 'code': 8, 'title': 'Observation'},
            {'abbr': 9, 'code': 9, 'title': 'Climatological'},
            {'abbr': 10, 'code': 10, 'title': 'Probability-weighted forecast'},
            {'abbr': 11, 'code': 11, 'title': 'Bias-corrected ensemble forecast'},
            {'abbr': 12, 'code': 12, 'title': 'Post-processed analysis'},
            {'abbr': 13, 'code': 13, 'title': 'Post-processed forecast'},
            {'abbr': 14, 'code': 14, 'title': 'Nowcast'},
            {'abbr': 15, 'code': 15, 'title': 'Hindcast'},
            {'abbr': 16, 'code': 16, 'title': 'Physical retrieval'},
            {'abbr': 17, 'code': 17, 'title': 'Regression analysis'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
