def load(h):
    return ({'abbr': 192, 'code': 192, 'title': 'Carbon Dioxide Net Ecosystem Exchange'},
            {'abbr': 193, 'code': 193, 'title': 'Carbon Dioxide Gross Primary Production'},
            {'abbr': 194, 'code': 194, 'title': 'Carbon Dioxide Ecosystem Respiration'},
            {'abbr': 195,
             'code': 195,
             'title': 'Flux of Carbon Dioxide Net Ecosystem Exchange'},
            {'abbr': 196,
             'code': 196,
             'title': 'Flux of Carbon Dioxide Ecosystem Respiration'},
            {'abbr': 197,
             'code': 197,
             'title': 'Flux of Carbon Dioxide Gross Primary Production'},
            {'abbr': 198,
             'code': 198,
             'title': 'GPP coefficient from Biogenic Flux Adjustment System'},
            {'abbr': 199,
             'code': 199,
             'title': 'Rec coefficient from Biogenic Flux Adjustment System'},
            {'abbr': None, 'code': 255, 'title': 'Missing'})
